import type { Customer } from "@/types"

// Totals are derived from orders.ts for each customerId.
// totalOrders = number of non-cancelled orders for that customer
// totalSpent = sum of `total` for paid/non-refunded orders for that customer
// lastOrderDate = most recent order createdAt

export const CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "Emma Rodriguez",
    email: "emma.rodriguez@email.com",
    phone: "512-334-7821",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=EmmaRodriguez",
    addresses: [
      {
        id: "addr-001-1",
        label: "Home",
        fullName: "Emma Rodriguez",
        address1: "2847 Lavender Lane",
        city: "Austin",
        state: "TX",
        zip: "78704",
        country: "United States",
        isDefault: true,
      },
      {
        id: "addr-001-2",
        label: "Office",
        fullName: "Emma Rodriguez",
        address1: "300 W 6th Street",
        address2: "Suite 1400",
        city: "Austin",
        state: "TX",
        zip: "78701",
        country: "United States",
        isDefault: false,
      },
    ],
    totalOrders: 3,
    totalSpent: 665.72,
    joinDate: "2025-06-12T10:00:00Z",
    lastOrderDate: "2026-04-01T10:00:00Z",
  },
  {
    id: "cust-002",
    name: "James Whitfield",
    email: "j.whitfield@promail.com",
    phone: "617-555-0192",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JamesWhitfield",
    addresses: [
      {
        id: "addr-002-1",
        label: "Home",
        fullName: "James Whitfield",
        address1: "104 Commonwealth Ave",
        address2: "Apt 3B",
        city: "Boston",
        state: "MA",
        zip: "02116",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 604.34,
    joinDate: "2025-08-03T10:00:00Z",
    lastOrderDate: "2026-03-31T09:00:00Z",
  },
  {
    id: "cust-003",
    name: "Priya Nair",
    email: "priya.nair@outlook.com",
    phone: "408-229-4410",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaNair",
    addresses: [
      {
        id: "addr-003-1",
        label: "Home",
        fullName: "Priya Nair",
        address1: "881 Saratoga Ave",
        city: "San Jose",
        state: "CA",
        zip: "95129",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 360.82,
    joinDate: "2025-09-20T10:00:00Z",
    lastOrderDate: "2026-03-29T09:00:00Z",
  },
  {
    id: "cust-004",
    name: "Marcus Chen",
    email: "marcus.chen@gmail.com",
    phone: "206-715-3380",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MarcusChen",
    addresses: [
      {
        id: "addr-004-1",
        label: "Office",
        fullName: "Marcus Chen",
        address1: "456 Pine Street",
        address2: "Suite 200",
        city: "Seattle",
        state: "WA",
        zip: "98101",
        country: "United States",
        isDefault: true,
      },
      {
        id: "addr-004-2",
        label: "Home",
        fullName: "Marcus Chen",
        address1: "1815 Queen Anne Ave N",
        city: "Seattle",
        state: "WA",
        zip: "98109",
        country: "United States",
        isDefault: false,
      },
    ],
    totalOrders: 2,
    totalSpent: 1924.98,
    joinDate: "2025-07-14T10:00:00Z",
    lastOrderDate: "2026-03-22T09:00:00Z",
  },
  {
    id: "cust-005",
    name: "Sarah Okafor",
    email: "sarah.okafor@icloud.com",
    phone: "404-887-5521",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SarahOkafor",
    addresses: [
      {
        id: "addr-005-1",
        label: "Home",
        fullName: "Sarah Okafor",
        address1: "1200 Peachtree St NE",
        address2: "Apt 8F",
        city: "Atlanta",
        state: "GA",
        zip: "30309",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 856.73,
    joinDate: "2025-05-28T10:00:00Z",
    lastOrderDate: "2026-04-01T08:00:00Z",
  },
  {
    id: "cust-006",
    name: "Tyler Russo",
    email: "tyler.russo@hotmail.com",
    phone: "773-441-9920",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=TylerRusso",
    addresses: [
      {
        id: "addr-006-1",
        label: "Home",
        fullName: "Tyler Russo",
        address1: "3302 N Lincoln Ave",
        city: "Chicago",
        state: "IL",
        zip: "60657",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 1,
    totalSpent: 141.68,
    joinDate: "2025-10-11T10:00:00Z",
    lastOrderDate: "2026-02-02T09:00:00Z",
  },
  {
    id: "cust-007",
    name: "Alicia Fontaine",
    email: "alicia.fontaine@gmail.com",
    phone: "504-228-1144",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AliciaFontaine",
    addresses: [
      {
        id: "addr-007-1",
        label: "Home",
        fullName: "Alicia Fontaine",
        address1: "719 Magazine Street",
        city: "New Orleans",
        state: "LA",
        zip: "70130",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 632.15,
    joinDate: "2025-11-05T10:00:00Z",
    lastOrderDate: "2026-01-21T09:00:00Z",
  },
  {
    id: "cust-008",
    name: "David Park",
    email: "dpark@workmail.com",
    phone: "310-558-6672",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DavidPark",
    addresses: [
      {
        id: "addr-008-1",
        label: "Primary",
        fullName: "David Park",
        address1: "8901 Wilshire Blvd",
        address2: "Penthouse 4",
        city: "Beverly Hills",
        state: "CA",
        zip: "90210",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 806.57,
    joinDate: "2025-04-18T10:00:00Z",
    lastOrderDate: "2026-03-31T11:00:00Z",
  },
  {
    id: "cust-009",
    name: "Rachel Kim",
    email: "rachel.kim@yahoo.com",
    phone: "212-883-4410",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RachelKim",
    addresses: [
      {
        id: "addr-009-1",
        label: "Home",
        fullName: "Rachel Kim",
        address1: "245 E 93rd Street",
        address2: "Apt 12A",
        city: "New York",
        state: "NY",
        zip: "10128",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 392.02,
    joinDate: "2025-07-22T10:00:00Z",
    lastOrderDate: "2026-03-27T09:00:00Z",
  },
  {
    id: "cust-010",
    name: "Brian Okonkwo",
    email: "brian.okonkwo@gmail.com",
    phone: "614-772-3388",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=BrianOkonkwo",
    addresses: [
      {
        id: "addr-010-1",
        label: "Home",
        fullName: "Brian Okonkwo",
        address1: "5511 Olentangy River Rd",
        city: "Columbus",
        state: "OH",
        zip: "43235",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 523.16,
    joinDate: "2025-09-08T10:00:00Z",
    lastOrderDate: "2026-01-27T09:00:00Z",
  },
  {
    id: "cust-011",
    name: "Lauren McAllister",
    email: "lauren.mac@email.com",
    phone: "503-774-2291",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LaurenMcAllister",
    addresses: [
      {
        id: "addr-011-1",
        label: "Home",
        fullName: "Lauren McAllister",
        address1: "1847 NW Thurman Street",
        city: "Portland",
        state: "OR",
        zip: "97209",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 1088.14,
    joinDate: "2025-06-30T10:00:00Z",
    lastOrderDate: "2026-03-30T09:00:00Z",
  },
  {
    id: "cust-012",
    name: "Kevin Tran",
    email: "kevintran@fastmail.com",
    phone: "713-661-5520",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KevinTran",
    addresses: [
      {
        id: "addr-012-1",
        label: "Home",
        fullName: "Kevin Tran",
        address1: "2231 Westheimer Rd",
        city: "Houston",
        state: "TX",
        zip: "77098",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 681.95,
    joinDate: "2025-08-17T10:00:00Z",
    lastOrderDate: "2026-03-30T09:00:00Z",
  },
  {
    id: "cust-013",
    name: "Maria Delgado",
    email: "maria.delgado@icloud.com",
    phone: "720-533-8812",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MariaDelgado",
    addresses: [
      {
        id: "addr-013-1",
        label: "Home",
        fullName: "Maria Delgado",
        address1: "3901 W 38th Ave",
        city: "Denver",
        state: "CO",
        zip: "80212",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 830.79,
    joinDate: "2025-05-04T10:00:00Z",
    lastOrderDate: "2026-03-26T09:00:00Z",
  },
  {
    id: "cust-014",
    name: "Steven Brooks",
    email: "s.brooks@corporatemail.net",
    phone: "602-447-3319",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=StevenBrooks",
    addresses: [
      {
        id: "addr-014-1",
        label: "Home",
        fullName: "Steven Brooks",
        address1: "8920 E Pinnacle Peak Rd",
        city: "Scottsdale",
        state: "AZ",
        zip: "85255",
        country: "United States",
        isDefault: true,
      },
      {
        id: "addr-014-2",
        label: "Office",
        fullName: "Steven Brooks",
        address1: "2525 E Camelback Rd",
        address2: "Suite 1000",
        city: "Phoenix",
        state: "AZ",
        zip: "85016",
        country: "United States",
        isDefault: false,
      },
    ],
    totalOrders: 2,
    totalSpent: 2016.46,
    joinDate: "2025-03-22T10:00:00Z",
    lastOrderDate: "2026-01-10T09:00:00Z",
  },
  {
    id: "cust-015",
    name: "Natalie Webb",
    email: "natalie.webb@email.com",
    phone: "305-448-7723",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=NatalieWebb",
    addresses: [
      {
        id: "addr-015-1",
        label: "Home",
        fullName: "Natalie Webb",
        address1: "1900 Brickell Ave",
        address2: "Apt 22D",
        city: "Miami",
        state: "FL",
        zip: "33129",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 298.74,
    joinDate: "2025-10-29T10:00:00Z",
    lastOrderDate: "2026-03-31T08:00:00Z",
  },
  {
    id: "cust-016",
    name: "Thomas Nielsen",
    email: "thomas.n@gmail.com",
    phone: "415-882-3311",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ThomasNielsen",
    addresses: [
      {
        id: "addr-016-1",
        label: "Home",
        fullName: "Thomas Nielsen",
        address1: "2200 Fillmore Street",
        city: "San Francisco",
        state: "CA",
        zip: "94115",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 1307.95,
    joinDate: "2025-04-10T10:00:00Z",
    lastOrderDate: "2026-03-28T09:00:00Z",
  },
  {
    id: "cust-017",
    name: "Aisha Johnson",
    email: "aisha.j@protonmail.com",
    phone: "901-441-2290",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AishaJohnson",
    addresses: [
      {
        id: "addr-017-1",
        label: "Home",
        fullName: "Aisha Johnson",
        address1: "655 Poplar Ave",
        city: "Memphis",
        state: "TN",
        zip: "38105",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 984.83,
    joinDate: "2025-07-07T10:00:00Z",
    lastOrderDate: "2026-03-27T09:00:00Z",
  },
  {
    id: "cust-018",
    name: "Colin Murphy",
    email: "colin.murphy@me.com",
    phone: "612-558-4430",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ColinMurphy",
    addresses: [
      {
        id: "addr-018-1",
        label: "Home",
        fullName: "Colin Murphy",
        address1: "2801 Lyndale Ave S",
        city: "Minneapolis",
        state: "MN",
        zip: "55408",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 291.56,
    joinDate: "2025-09-14T10:00:00Z",
    lastOrderDate: "2026-04-01T09:00:00Z",
  },
  {
    id: "cust-019",
    name: "Diane Foster",
    email: "diane.foster@gmail.com",
    phone: "303-228-9901",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DianeFoster",
    addresses: [
      {
        id: "addr-019-1",
        label: "Home",
        fullName: "Diane Foster",
        address1: "1710 Wazee Street",
        city: "Denver",
        state: "CO",
        zip: "80202",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 998.15,
    joinDate: "2025-02-28T10:00:00Z",
    lastOrderDate: "2026-03-29T09:00:00Z",
  },
  {
    id: "cust-020",
    name: "Marcus Hill",
    email: "marcus.hill@email.net",
    phone: "615-334-8823",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MarcusHill",
    addresses: [
      {
        id: "addr-020-1",
        label: "Home",
        fullName: "Marcus Hill",
        address1: "420 Church Street",
        address2: "Unit 5A",
        city: "Nashville",
        state: "TN",
        zip: "37219",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 1306.16,
    joinDate: "2025-06-01T10:00:00Z",
    lastOrderDate: "2026-04-01T11:00:00Z",
  },
  {
    id: "cust-021",
    name: "Simone Laurent",
    email: "simone.l@outlook.com",
    phone: "617-923-4415",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SimoneLaurent",
    addresses: [
      {
        id: "addr-021-1",
        label: "Home",
        fullName: "Simone Laurent",
        address1: "88 Marlborough Street",
        city: "Boston",
        state: "MA",
        zip: "02116",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 2,
    totalSpent: 376.02,
    joinDate: "2025-11-18T10:00:00Z",
    lastOrderDate: "2026-03-30T09:00:00Z",
  },
  {
    id: "cust-022",
    name: "Jason Rivera",
    email: "jrivera@yahoo.com",
    phone: "787-229-5510",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JasonRivera",
    addresses: [
      {
        id: "addr-022-1",
        label: "Home",
        fullName: "Jason Rivera",
        address1: "1503 Ashford Ave",
        city: "San Juan",
        state: "PR",
        zip: "00911",
        country: "United States",
        isDefault: true,
      },
    ],
    totalOrders: 3,
    totalSpent: 1379.26,
    joinDate: "2025-05-15T10:00:00Z",
    lastOrderDate: "2026-03-23T09:00:00Z",
  },
]
