import type { AppNotification } from "@/types"

// All timestamps are within the last 24 hours relative to 2026-04-01T12:00:00Z
function hoursAgo(h: number): string {
  const base = new Date("2026-04-01T12:00:00Z")
  base.setMinutes(base.getMinutes() - Math.round(h * 60))
  return base.toISOString()
}

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-001",
    type: "success",
    title: "New Order Received",
    message: "Order #ORD-2026-0550 placed by Emma Rodriguez for $368.03.",
    link: "/orders/order-001",
    read: false,
    createdAt: hoursAgo(0.5),
  },
  {
    id: "notif-002",
    type: "info",
    title: "New Customer Sign-Up",
    message: "Colin Murphy created an account and placed his first order.",
    link: "/customers/cust-018",
    read: false,
    createdAt: hoursAgo(1.0),
  },
  {
    id: "notif-003",
    type: "success",
    title: "Order Shipped",
    message: "Order #ORD-2026-0548 for Priya Nair has been handed to UPS. Tracking: 1Z2A3B4C5D6E7F8G.",
    link: "/orders/order-003",
    read: false,
    createdAt: hoursAgo(1.5),
  },
  {
    id: "notif-004",
    type: "warning",
    title: "Low Stock Alert",
    message: "Boucle Accent Armchair (Cream) has only 28 units remaining. Consider reordering soon.",
    link: "/products/prod-014",
    read: false,
    createdAt: hoursAgo(2.0),
  },
  {
    id: "notif-005",
    type: "success",
    title: "New Order Received",
    message: "Order #ORD-2026-0549 placed by James Whitfield for $290.42.",
    link: "/orders/order-002",
    read: false,
    createdAt: hoursAgo(2.5),
  },
  {
    id: "notif-006",
    type: "warning",
    title: "Low Stock Alert",
    message: "Studio Monitor Bookshelf Speakers (Black) — only 29 units left across all variants.",
    link: "/products/prod-029",
    read: true,
    createdAt: hoursAgo(3.5),
  },
  {
    id: "notif-007",
    type: "info",
    title: "Order Delivered",
    message: "Order #ORD-2026-0547 for Marcus Chen has been delivered. Delivery confirmed by carrier.",
    link: "/orders/order-004",
    read: true,
    createdAt: hoursAgo(4.0),
  },
  {
    id: "notif-008",
    type: "error",
    title: "Payment Failed",
    message: "Order #ORD-2026-0504 for Marcus Hill has an unpaid balance of $381.49. Payment retry pending.",
    link: "/orders/order-047",
    read: false,
    createdAt: hoursAgo(4.5),
  },
  {
    id: "notif-009",
    type: "success",
    title: "New Order Received",
    message: "Order #ORD-2026-0503 placed by Diane Foster for $151.88.",
    link: "/orders/order-048",
    read: true,
    createdAt: hoursAgo(5.5),
  },
  {
    id: "notif-010",
    type: "info",
    title: "New Customer Sign-Up",
    message: "Natalie Webb created a new account. Welcome email sent.",
    link: "/customers/cust-015",
    read: true,
    createdAt: hoursAgo(7.0),
  },
  {
    id: "notif-011",
    type: "warning",
    title: "Low Stock Alert",
    message: "Apex Slim Laptop 15 (Space Gray) — inventory down to 34 units. Lead time is 3 weeks.",
    link: "/products/prod-002",
    read: true,
    createdAt: hoursAgo(8.5),
  },
  {
    id: "notif-012",
    type: "success",
    title: "Order Shipped",
    message: "Order #ORD-2026-0497 for Aisha Johnson is on its way via UPS. Tracking: 1ZA9B8C7D6E5F4G3.",
    link: "/orders/order-054",
    read: false,
    createdAt: hoursAgo(10.0),
  },
  {
    id: "notif-013",
    type: "info",
    title: "Product Review Submitted",
    message: "A new 5-star review was submitted for SoundWave Pro X Wireless Headphones by a verified buyer.",
    link: "/products/prod-001",
    read: true,
    createdAt: hoursAgo(12.0),
  },
  {
    id: "notif-014",
    type: "success",
    title: "New Order Received",
    message: "Order #ORD-2026-0496 placed by Colin Murphy for $129.57.",
    link: "/orders/order-055",
    read: true,
    createdAt: hoursAgo(16.0),
  },
  {
    id: "notif-015",
    type: "warning",
    title: "Low Stock Alert",
    message: "Heritage Selvedge Denim Jeans (Raw Indigo, 28x30) — only 42 total units remaining in all washes.",
    link: "/products/prod-011",
    read: true,
    createdAt: hoursAgo(22.0),
  },
]
