import type { Order } from "@/types"

// Helper to build ISO date strings relative to today (2026-04-01)
// daysAgo: positive = past, negative = future
function daysFromNow(daysAgo: number, hoursOffset = 0): string {
  const base = new Date("2026-04-01T12:00:00Z")
  base.setDate(base.getDate() - daysAgo)
  base.setHours(base.getHours() + hoursOffset)
  return base.toISOString()
}

function futureDate(daysAhead: number): string {
  const base = new Date("2026-04-01T12:00:00Z")
  base.setDate(base.getDate() + daysAhead)
  return base.toISOString()
}

export const ORDERS: Order[] = [
  // ── Recent / Pending ───────────────────────────────────────────────────────
  {
    id: "order-001",
    orderNumber: "ORD-2026-0550",
    customerId: "cust-001",
    customerName: "Emma Rodriguez",
    customerEmail: "emma.rodriguez@email.com",
    items: [
      { productId: "prod-001", productName: "SoundWave Pro X Wireless Headphones", productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80", quantity: 1, price: 249.99, selectedVariants: { Color: "Midnight Black" } },
      { productId: "prod-021", productName: "Heritage Leather Bifold Wallet", productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", quantity: 1, price: 89.99, selectedVariants: { "Leather Color": "Tan" } },
    ],
    shippingAddress: { fullName: "Emma Rodriguez", email: "emma.rodriguez@email.com", phone: "512-334-7821", address1: "2847 Lavender Lane", city: "Austin", state: "TX", zip: "78704", country: "United States" },
    subtotal: 339.98,
    shipping: 0,
    tax: 28.05,
    total: 368.03,
    discount: 0,
    status: "pending",
    paymentStatus: "paid",
    timeline: [{ status: "pending", date: daysFromNow(0, -2), note: "Order placed successfully" }],
    createdAt: daysFromNow(0, -2),
    updatedAt: daysFromNow(0, -2),
    estimatedDelivery: futureDate(5),
  },
  {
    id: "order-002",
    orderNumber: "ORD-2026-0549",
    customerId: "cust-002",
    customerName: "James Whitfield",
    customerEmail: "j.whitfield@promail.com",
    items: [
      { productId: "prod-007", productName: "Meridian Merino Crewneck Sweater", productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80", quantity: 2, price: 129.99, selectedVariants: { Size: "L", Color: "Charcoal" } },
    ],
    shippingAddress: { fullName: "James Whitfield", email: "j.whitfield@promail.com", phone: "617-555-0192", address1: "104 Commonwealth Ave", address2: "Apt 3B", city: "Boston", state: "MA", zip: "02116", country: "United States" },
    subtotal: 259.98,
    shipping: 8.99,
    tax: 21.45,
    total: 290.42,
    discount: 0,
    status: "processing",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(1, -3), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(0, -6), note: "Payment confirmed, preparing your order" },
    ],
    createdAt: daysFromNow(1, -3),
    updatedAt: daysFromNow(0, -6),
    estimatedDelivery: futureDate(4),
  },
  {
    id: "order-003",
    orderNumber: "ORD-2026-0548",
    customerId: "cust-003",
    customerName: "Priya Nair",
    customerEmail: "priya.nair@outlook.com",
    items: [
      { productId: "prod-012", productName: "Sanctum Weighted Blanket", productImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", quantity: 1, price: 119.99, selectedVariants: { Color: "Dusty Blue" } },
      { productId: "prod-015", productName: "Ceramic Diffuser & Oil Set", productImage: "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80", quantity: 1, price: 79.99, selectedVariants: { "Ceramic Glaze": "Sage Matte" } },
    ],
    shippingAddress: { fullName: "Priya Nair", email: "priya.nair@outlook.com", phone: "408-229-4410", address1: "881 Saratoga Ave", city: "San Jose", state: "CA", zip: "95129", country: "United States" },
    subtotal: 199.98,
    shipping: 0,
    tax: 18.50,
    total: 218.48,
    discount: 0,
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(3), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(2, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(1), note: "Package handed to UPS — Tracking: 1Z2A3B4C5D6E7F8G" },
    ],
    createdAt: daysFromNow(3),
    updatedAt: daysFromNow(1),
    estimatedDelivery: futureDate(2),
  },
  {
    id: "order-004",
    orderNumber: "ORD-2026-0547",
    customerId: "cust-004",
    customerName: "Marcus Chen",
    customerEmail: "marcus.chen@gmail.com",
    items: [
      { productId: "prod-002", productName: "Apex Slim Laptop 15", productImage: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80", quantity: 1, price: 1299.99, selectedVariants: { Color: "Space Gray" } },
    ],
    shippingAddress: { fullName: "Marcus Chen", email: "marcus.chen@gmail.com", phone: "206-715-3380", address1: "456 Pine Street", address2: "Suite 200", city: "Seattle", state: "WA", zip: "98101", country: "United States" },
    subtotal: 1299.99,
    shipping: 0,
    tax: 130.00,
    total: 1429.99,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(10), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(9, 3), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(7), note: "Package shipped via FedEx Priority — Tracking: 7489230192847" },
      { status: "delivered", date: daysFromNow(4), note: "Package delivered — Left at front door" },
    ],
    createdAt: daysFromNow(10),
    updatedAt: daysFromNow(4),
    estimatedDelivery: daysFromNow(4),
  },
  {
    id: "order-005",
    orderNumber: "ORD-2026-0546",
    customerId: "cust-005",
    customerName: "Sarah Okafor",
    customerEmail: "sarah.okafor@icloud.com",
    items: [
      { productId: "prod-018", productName: "FlexCore Yoga Mat Pro", productImage: "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80", quantity: 1, price: 79.99, selectedVariants: { Color: "Deep Plum" } },
      { productId: "prod-027", productName: "Merino Running Socks 3-Pack", productImage: "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80", quantity: 2, price: 34.99, selectedVariants: { "Shoe Size": "US 6.5-9", Color: "Black/Gray" } },
    ],
    shippingAddress: { fullName: "Sarah Okafor", email: "sarah.okafor@icloud.com", phone: "404-887-5521", address1: "1200 Peachtree St NE", address2: "Apt 8F", city: "Atlanta", state: "GA", zip: "30309", country: "United States" },
    subtotal: 149.97,
    shipping: 5.99,
    tax: 12.40,
    total: 168.36,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(12), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(11, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(9), note: "Package shipped via USPS Priority Mail" },
      { status: "delivered", date: daysFromNow(6), note: "Package delivered" },
    ],
    createdAt: daysFromNow(12),
    updatedAt: daysFromNow(6),
    estimatedDelivery: daysFromNow(6),
  },
  {
    id: "order-006",
    orderNumber: "ORD-2026-0545",
    customerId: "cust-006",
    customerName: "Tyler Russo",
    customerEmail: "tyler.russo@hotmail.com",
    items: [
      { productId: "prod-022", productName: "Navigator Canvas Backpack", productImage: "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80", quantity: 1, price: 179.99, selectedVariants: { Color: "Waxed Navy" } },
    ],
    shippingAddress: { fullName: "Tyler Russo", email: "tyler.russo@hotmail.com", phone: "773-441-9920", address1: "3302 N Lincoln Ave", city: "Chicago", state: "IL", zip: "60657", country: "United States" },
    subtotal: 179.99,
    shipping: 0,
    tax: 16.20,
    total: 196.19,
    discount: 0,
    status: "cancelled",
    paymentStatus: "refunded",
    timeline: [
      { status: "pending", date: daysFromNow(14), note: "Order placed successfully" },
      { status: "cancelled", date: daysFromNow(13, 2), note: "Order cancelled at customer request. Full refund issued." },
    ],
    createdAt: daysFromNow(14),
    updatedAt: daysFromNow(13, 2),
    estimatedDelivery: daysFromNow(9),
  },
  {
    id: "order-007",
    orderNumber: "ORD-2026-0544",
    customerId: "cust-007",
    customerName: "Alicia Fontaine",
    customerEmail: "alicia.fontaine@gmail.com",
    items: [
      { productId: "prod-023", productName: "Luxury Cashmere Scarf", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 2, price: 119.99, selectedVariants: { Color: "Camel" } },
      { productId: "prod-024", productName: "Minimal Steel Mesh Watch", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 179.99, selectedVariants: { "Dial Color": "White" } },
    ],
    shippingAddress: { fullName: "Alicia Fontaine", email: "alicia.fontaine@gmail.com", phone: "504-228-1144", address1: "719 Magazine Street", city: "New Orleans", state: "LA", zip: "70130", country: "United States" },
    subtotal: 419.97,
    shipping: 0,
    tax: 37.80,
    total: 457.77,
    discount: 21.00,
    promoCode: "WINTER15",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(15), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(14, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(12), note: "Package shipped via UPS Ground" },
      { status: "delivered", date: daysFromNow(9), note: "Package delivered — Signed for by resident" },
    ],
    createdAt: daysFromNow(15),
    updatedAt: daysFromNow(9),
    estimatedDelivery: daysFromNow(9),
  },
  {
    id: "order-008",
    orderNumber: "ORD-2026-0543",
    customerId: "cust-008",
    customerName: "David Park",
    customerEmail: "dpark@workmail.com",
    items: [
      { productId: "prod-005", productName: "PulseWatch GT Smartwatch", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 299.99, selectedVariants: { "Band Color": "Black" } },
      { productId: "prod-028", productName: "Titanium Carabiner Keychain", productImage: "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80", quantity: 1, price: 39.99, selectedVariants: { Finish: "Natural Titanium" } },
    ],
    shippingAddress: { fullName: "David Park", email: "dpark@workmail.com", phone: "310-558-6672", address1: "8901 Wilshire Blvd", address2: "Penthouse 4", city: "Beverly Hills", state: "CA", zip: "90210", country: "United States" },
    subtotal: 339.98,
    shipping: 0,
    tax: 30.60,
    total: 370.58,
    discount: 0,
    status: "processing",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(1, -1), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(0, -8), note: "Payment confirmed, preparing your order" },
    ],
    createdAt: daysFromNow(1, -1),
    updatedAt: daysFromNow(0, -8),
    estimatedDelivery: futureDate(5),
  },
  {
    id: "order-009",
    orderNumber: "ORD-2026-0542",
    customerId: "cust-009",
    customerName: "Rachel Kim",
    customerEmail: "rachel.kim@yahoo.com",
    items: [
      { productId: "prod-010", productName: "Essential Organic Tee 3-Pack", productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80", quantity: 1, price: 59.99, selectedVariants: { Size: "S", "Color Pack": "Earth Tones" } },
      { productId: "prod-009", productName: "Linen Relaxed Chino Trousers", productImage: "https://images.unsplash.com/photo-1594938298603-f8a3d0040133?w=800&q=80", quantity: 1, price: 89.99, selectedVariants: { Size: "28", Color: "Sand" } },
    ],
    shippingAddress: { fullName: "Rachel Kim", email: "rachel.kim@yahoo.com", phone: "212-883-4410", address1: "245 E 93rd Street", address2: "Apt 12A", city: "New York", state: "NY", zip: "10128", country: "United States" },
    subtotal: 149.98,
    shipping: 0,
    tax: 13.35,
    total: 163.33,
    discount: 0,
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(5), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(4, 6), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(3), note: "Package shipped via USPS Priority — Tracking: 9400111899225014861234" },
    ],
    createdAt: daysFromNow(5),
    updatedAt: daysFromNow(3),
    estimatedDelivery: futureDate(1),
  },
  {
    id: "order-010",
    orderNumber: "ORD-2026-0541",
    customerId: "cust-010",
    customerName: "Brian Okonkwo",
    customerEmail: "brian.okonkwo@gmail.com",
    items: [
      { productId: "prod-019", productName: "PowerLift Adjustable Dumbbells", productImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80", quantity: 1, price: 349.99, selectedVariants: {} },
      { productId: "prod-032", productName: "Resistance Band Training Set", productImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80", quantity: 1, price: 49.99, selectedVariants: { Color: "Black" } },
    ],
    shippingAddress: { fullName: "Brian Okonkwo", email: "brian.okonkwo@gmail.com", phone: "614-772-3388", address1: "5511 Olentangy River Rd", city: "Columbus", state: "OH", zip: "43235", country: "United States" },
    subtotal: 399.98,
    shipping: 0,
    tax: 35.99,
    total: 435.97,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(18), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(17, 3), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(15), note: "Package shipped via FedEx Ground" },
      { status: "delivered", date: daysFromNow(11), note: "Package delivered" },
    ],
    createdAt: daysFromNow(18),
    updatedAt: daysFromNow(11),
    estimatedDelivery: daysFromNow(11),
  },
  {
    id: "order-011",
    orderNumber: "ORD-2026-0540",
    customerId: "cust-011",
    customerName: "Lauren McAllister",
    customerEmail: "lauren.mac@email.com",
    items: [
      { productId: "prod-013", productName: "Artisan Pour-Over Coffee Station", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 1, price: 149.99, selectedVariants: { "Wood Finish": "Natural Walnut" } },
    ],
    shippingAddress: { fullName: "Lauren McAllister", email: "lauren.mac@email.com", phone: "503-774-2291", address1: "1847 NW Thurman Street", city: "Portland", state: "OR", zip: "97209", country: "United States" },
    subtotal: 149.99,
    shipping: 0,
    tax: 13.50,
    total: 163.49,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(20), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(19, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(17), note: "Package shipped via UPS" },
      { status: "delivered", date: daysFromNow(14), note: "Package delivered — Left at door" },
    ],
    createdAt: daysFromNow(20),
    updatedAt: daysFromNow(14),
    estimatedDelivery: daysFromNow(14),
  },
  {
    id: "order-012",
    orderNumber: "ORD-2026-0539",
    customerId: "cust-012",
    customerName: "Kevin Tran",
    customerEmail: "kevintran@fastmail.com",
    items: [
      { productId: "prod-004", productName: "NovaPad Ultra Tablet 11", productImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80", quantity: 1, price: 479.99, selectedVariants: { Color: "Graphite" } },
    ],
    shippingAddress: { fullName: "Kevin Tran", email: "kevintran@fastmail.com", phone: "713-661-5520", address1: "2231 Westheimer Rd", city: "Houston", state: "TX", zip: "77098", country: "United States" },
    subtotal: 479.99,
    shipping: 0,
    tax: 39.60,
    total: 519.59,
    discount: 0,
    status: "processing",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(2), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(1, 8), note: "Payment confirmed, preparing your order" },
    ],
    createdAt: daysFromNow(2),
    updatedAt: daysFromNow(1, 8),
    estimatedDelivery: futureDate(4),
  },
  {
    id: "order-013",
    orderNumber: "ORD-2026-0538",
    customerId: "cust-013",
    customerName: "Maria Delgado",
    customerEmail: "maria.delgado@icloud.com",
    items: [
      { productId: "prod-008", productName: "Altitude Waterproof Shell Jacket", productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", quantity: 1, price: 289.99, selectedVariants: { Size: "M", Color: "Alpine Red" } },
      { productId: "prod-017", productName: "TrailBlazer Carbon Trekking Poles", productImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80", quantity: 1, price: 119.99, selectedVariants: { Color: "Forest Green" } },
    ],
    shippingAddress: { fullName: "Maria Delgado", email: "maria.delgado@icloud.com", phone: "720-533-8812", address1: "3901 W 38th Ave", city: "Denver", state: "CO", zip: "80212", country: "United States" },
    subtotal: 409.98,
    shipping: 0,
    tax: 34.85,
    total: 444.83,
    discount: 41.00,
    promoCode: "TRAIL10",
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(6), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(5, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(4), note: "Package shipped via FedEx — Tracking: 7749302938475" },
    ],
    createdAt: daysFromNow(6),
    updatedAt: daysFromNow(4),
    estimatedDelivery: futureDate(2),
  },
  {
    id: "order-014",
    orderNumber: "ORD-2026-0537",
    customerId: "cust-014",
    customerName: "Steven Brooks",
    customerEmail: "s.brooks@corporatemail.net",
    items: [
      { productId: "prod-016", productName: "Modular Bamboo Shelving System", productImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", quantity: 1, price: 229.99, selectedVariants: { Configuration: "2-Bay Linked" } },
      { productId: "prod-031", productName: "Bamboo Cutting Board Set", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 1, price: 69.99, selectedVariants: {} },
    ],
    shippingAddress: { fullName: "Steven Brooks", email: "s.brooks@corporatemail.net", phone: "602-447-3319", address1: "8920 E Pinnacle Peak Rd", city: "Scottsdale", state: "AZ", zip: "85255", country: "United States" },
    subtotal: 299.98,
    shipping: 0,
    tax: 27.00,
    total: 326.98,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(22), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(21, 6), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(19), note: "Package shipped via UPS Ground" },
      { status: "delivered", date: daysFromNow(15), note: "Package delivered — Left with neighbor" },
    ],
    createdAt: daysFromNow(22),
    updatedAt: daysFromNow(15),
    estimatedDelivery: daysFromNow(15),
  },
  {
    id: "order-015",
    orderNumber: "ORD-2026-0536",
    customerId: "cust-015",
    customerName: "Natalie Webb",
    customerEmail: "natalie.webb@email.com",
    items: [
      { productId: "prod-025", productName: "Polarized Aviator Sunglasses", productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", quantity: 1, price: 149.99, selectedVariants: { "Frame Color": "Gold/Brown" } },
    ],
    shippingAddress: { fullName: "Natalie Webb", email: "natalie.webb@email.com", phone: "305-448-7723", address1: "1900 Brickell Ave", address2: "Apt 22D", city: "Miami", state: "FL", zip: "33129", country: "United States" },
    subtotal: 149.99,
    shipping: 0,
    tax: 10.05,
    total: 160.04,
    discount: 0,
    status: "pending",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(0, -4), note: "Order placed successfully" },
    ],
    createdAt: daysFromNow(0, -4),
    updatedAt: daysFromNow(0, -4),
    estimatedDelivery: futureDate(5),
  },
  {
    id: "order-016",
    orderNumber: "ORD-2026-0535",
    customerId: "cust-001",
    customerName: "Emma Rodriguez",
    customerEmail: "emma.rodriguez@email.com",
    items: [
      { productId: "prod-011", productName: "Heritage Selvedge Denim Jeans", productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", quantity: 1, price: 195.00, selectedVariants: { "Waist x Inseam": "28x30", Wash: "Raw Indigo" } },
    ],
    shippingAddress: { fullName: "Emma Rodriguez", email: "emma.rodriguez@email.com", phone: "512-334-7821", address1: "2847 Lavender Lane", city: "Austin", state: "TX", zip: "78704", country: "United States" },
    subtotal: 195.00,
    shipping: 0,
    tax: 16.10,
    total: 211.10,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(30), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(29, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(27), note: "Package shipped via USPS Priority" },
      { status: "delivered", date: daysFromNow(24), note: "Package delivered" },
    ],
    createdAt: daysFromNow(30),
    updatedAt: daysFromNow(24),
    estimatedDelivery: daysFromNow(24),
  },
  {
    id: "order-017",
    orderNumber: "ORD-2026-0534",
    customerId: "cust-016",
    customerName: "Thomas Nielsen",
    customerEmail: "thomas.n@gmail.com",
    items: [
      { productId: "prod-003", productName: "VisionCam 4K Action Camera", productImage: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80", quantity: 1, price: 349.99, selectedVariants: { Color: "Stealth Black" } },
      { productId: "prod-020", productName: "Aero Road Cycling Helmet", productImage: "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80", quantity: 1, price: 189.99, selectedVariants: { Size: "M (55-59 cm)", Color: "Matte Black" } },
    ],
    shippingAddress: { fullName: "Thomas Nielsen", email: "thomas.n@gmail.com", phone: "415-882-3311", address1: "2200 Fillmore Street", city: "San Francisco", state: "CA", zip: "94115", country: "United States" },
    subtotal: 539.98,
    shipping: 0,
    tax: 48.60,
    total: 588.58,
    discount: 54.00,
    promoCode: "RIDE10",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(25), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(24, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(22), note: "Package shipped via FedEx Priority" },
      { status: "delivered", date: daysFromNow(19), note: "Package delivered" },
    ],
    createdAt: daysFromNow(25),
    updatedAt: daysFromNow(19),
    estimatedDelivery: daysFromNow(19),
  },
  {
    id: "order-018",
    orderNumber: "ORD-2026-0533",
    customerId: "cust-017",
    customerName: "Aisha Johnson",
    customerEmail: "aisha.j@protonmail.com",
    items: [
      { productId: "prod-029", productName: "Studio Monitor Bookshelf Speakers", productImage: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80", quantity: 1, price: 449.99, selectedVariants: { Color: "Black" } },
    ],
    shippingAddress: { fullName: "Aisha Johnson", email: "aisha.j@protonmail.com", phone: "901-441-2290", address1: "655 Poplar Ave", city: "Memphis", state: "TN", zip: "38105", country: "United States" },
    subtotal: 449.99,
    shipping: 0,
    tax: 40.50,
    total: 490.49,
    discount: 0,
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(7), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(6, 7), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(5), note: "Package shipped via UPS Ground — Tracking: 1Z9X8W7V6U5T4S3" },
    ],
    createdAt: daysFromNow(7),
    updatedAt: daysFromNow(5),
    estimatedDelivery: futureDate(2),
  },
  {
    id: "order-019",
    orderNumber: "ORD-2026-0532",
    customerId: "cust-018",
    customerName: "Colin Murphy",
    customerEmail: "colin.murphy@me.com",
    items: [
      { productId: "prod-006", productName: "PixelFrame Digital Art Display", productImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80", quantity: 1, price: 399.99, selectedVariants: { "Frame Finish": "Walnut Wood" } },
    ],
    shippingAddress: { fullName: "Colin Murphy", email: "colin.murphy@me.com", phone: "612-558-4430", address1: "2801 Lyndale Ave S", city: "Minneapolis", state: "MN", zip: "55408", country: "United States" },
    subtotal: 399.99,
    shipping: 0,
    tax: 31.99,
    total: 431.98,
    discount: 0,
    status: "cancelled",
    paymentStatus: "refunded",
    timeline: [
      { status: "pending", date: daysFromNow(8), note: "Order placed successfully" },
      { status: "cancelled", date: daysFromNow(8, 3), note: "Order cancelled — Item out of stock. Full refund issued." },
    ],
    createdAt: daysFromNow(8),
    updatedAt: daysFromNow(8, 3),
    estimatedDelivery: daysFromNow(3),
  },
  {
    id: "order-020",
    orderNumber: "ORD-2026-0531",
    customerId: "cust-019",
    customerName: "Diane Foster",
    customerEmail: "diane.foster@gmail.com",
    items: [
      { productId: "prod-026", productName: "Compact Espresso Machine", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 1, price: 399.99, selectedVariants: { Color: "Brushed Stainless" } },
      { productId: "prod-013", productName: "Artisan Pour-Over Coffee Station", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 1, price: 149.99, selectedVariants: { "Wood Finish": "Dark Walnut" } },
    ],
    shippingAddress: { fullName: "Diane Foster", email: "diane.foster@gmail.com", phone: "303-228-9901", address1: "1710 Wazee Street", city: "Denver", state: "CO", zip: "80202", country: "United States" },
    subtotal: 549.98,
    shipping: 0,
    tax: 46.75,
    total: 596.73,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(35), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(34, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(32), note: "Package shipped via FedEx" },
      { status: "delivered", date: daysFromNow(28), note: "Package delivered" },
    ],
    createdAt: daysFromNow(35),
    updatedAt: daysFromNow(28),
    estimatedDelivery: daysFromNow(28),
  },
  {
    id: "order-021",
    orderNumber: "ORD-2026-0530",
    customerId: "cust-020",
    customerName: "Marcus Hill",
    customerEmail: "marcus.hill@email.net",
    items: [
      { productId: "prod-014", productName: "Boucle Accent Armchair", productImage: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80", quantity: 1, price: 649.99, selectedVariants: { "Fabric Color": "Cream" } },
    ],
    shippingAddress: { fullName: "Marcus Hill", email: "marcus.hill@email.net", phone: "615-334-8823", address1: "420 Church Street", address2: "Unit 5A", city: "Nashville", state: "TN", zip: "37219", country: "United States" },
    subtotal: 649.99,
    shipping: 19.99,
    tax: 58.50,
    total: 728.48,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(40), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(39, 6), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(37), note: "Item dispatched via White Glove Delivery service" },
      { status: "delivered", date: daysFromNow(33), note: "Item delivered and assembled by delivery team" },
    ],
    createdAt: daysFromNow(40),
    updatedAt: daysFromNow(33),
    estimatedDelivery: daysFromNow(33),
  },
  {
    id: "order-022",
    orderNumber: "ORD-2026-0529",
    customerId: "cust-021",
    customerName: "Simone Laurent",
    customerEmail: "simone.l@outlook.com",
    items: [
      { productId: "prod-030", productName: "Performance Running Jacket", productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", quantity: 1, price: 129.99, selectedVariants: { Size: "S", Color: "Coral Red" } },
      { productId: "prod-027", productName: "Merino Running Socks 3-Pack", productImage: "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80", quantity: 1, price: 34.99, selectedVariants: { "Shoe Size": "US 4-6", Color: "Black/Gray" } },
    ],
    shippingAddress: { fullName: "Simone Laurent", email: "simone.l@outlook.com", phone: "617-923-4415", address1: "88 Marlborough Street", city: "Boston", state: "MA", zip: "02116", country: "United States" },
    subtotal: 164.98,
    shipping: 0,
    tax: 14.85,
    total: 179.83,
    discount: 0,
    status: "processing",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(2, -3), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(1, 5), note: "Payment confirmed, preparing your order" },
    ],
    createdAt: daysFromNow(2, -3),
    updatedAt: daysFromNow(1, 5),
    estimatedDelivery: futureDate(5),
  },
  {
    id: "order-023",
    orderNumber: "ORD-2026-0528",
    customerId: "cust-022",
    customerName: "Jason Rivera",
    customerEmail: "jrivera@yahoo.com",
    items: [
      { productId: "prod-001", productName: "SoundWave Pro X Wireless Headphones", productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80", quantity: 1, price: 249.99, selectedVariants: { Color: "Pearl White" } },
      { productId: "prod-005", productName: "PulseWatch GT Smartwatch", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 299.99, selectedVariants: { "Band Color": "Slate Blue" } },
    ],
    shippingAddress: { fullName: "Jason Rivera", email: "jrivera@yahoo.com", phone: "787-229-5510", address1: "1503 Ashford Ave", city: "San Juan", state: "PR", zip: "00911", country: "United States" },
    subtotal: 549.98,
    shipping: 9.99,
    tax: 47.25,
    total: 607.22,
    discount: 0,
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(9), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(8, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(7), note: "Package shipped via USPS Priority Mail International" },
    ],
    createdAt: daysFromNow(9),
    updatedAt: daysFromNow(7),
    estimatedDelivery: futureDate(3),
  },
  {
    id: "order-024",
    orderNumber: "ORD-2026-0527",
    customerId: "cust-004",
    customerName: "Marcus Chen",
    customerEmail: "marcus.chen@gmail.com",
    items: [
      { productId: "prod-029", productName: "Studio Monitor Bookshelf Speakers", productImage: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80", quantity: 1, price: 449.99, selectedVariants: { Color: "White" } },
    ],
    shippingAddress: { fullName: "Marcus Chen", email: "marcus.chen@gmail.com", phone: "206-715-3380", address1: "456 Pine Street", address2: "Suite 200", city: "Seattle", state: "WA", zip: "98101", country: "United States" },
    subtotal: 449.99,
    shipping: 0,
    tax: 45.00,
    total: 494.99,
    discount: 45.00,
    promoCode: "AUDIO10",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(45), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(44, 3), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(42), note: "Package shipped via FedEx" },
      { status: "delivered", date: daysFromNow(39), note: "Package delivered" },
    ],
    createdAt: daysFromNow(45),
    updatedAt: daysFromNow(39),
    estimatedDelivery: daysFromNow(39),
  },
  {
    id: "order-025",
    orderNumber: "ORD-2026-0526",
    customerId: "cust-003",
    customerName: "Priya Nair",
    customerEmail: "priya.nair@outlook.com",
    items: [
      { productId: "prod-007", productName: "Meridian Merino Crewneck Sweater", productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80", quantity: 1, price: 129.99, selectedVariants: { Size: "XS", Color: "Dusty Rose" } },
    ],
    shippingAddress: { fullName: "Priya Nair", email: "priya.nair@outlook.com", phone: "408-229-4410", address1: "881 Saratoga Ave", city: "San Jose", state: "CA", zip: "95129", country: "United States" },
    subtotal: 129.99,
    shipping: 0,
    tax: 12.35,
    total: 142.34,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(50), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(49, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(47), note: "Package shipped via USPS" },
      { status: "delivered", date: daysFromNow(44), note: "Package delivered" },
    ],
    createdAt: daysFromNow(50),
    updatedAt: daysFromNow(44),
    estimatedDelivery: daysFromNow(44),
  },
  {
    id: "order-026",
    orderNumber: "ORD-2026-0525",
    customerId: "cust-005",
    customerName: "Sarah Okafor",
    customerEmail: "sarah.okafor@icloud.com",
    items: [
      { productId: "prod-012", productName: "Sanctum Weighted Blanket", productImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", quantity: 2, price: 119.99, selectedVariants: { Color: "Slate Gray" } },
    ],
    shippingAddress: { fullName: "Sarah Okafor", email: "sarah.okafor@icloud.com", phone: "404-887-5521", address1: "1200 Peachtree St NE", address2: "Apt 8F", city: "Atlanta", state: "GA", zip: "30309", country: "United States" },
    subtotal: 239.98,
    shipping: 0,
    tax: 21.60,
    total: 261.58,
    discount: 24.00,
    promoCode: "SLEEP10",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(55), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(54, 6), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(52), note: "Package shipped via UPS Ground" },
      { status: "delivered", date: daysFromNow(48), note: "Package delivered" },
    ],
    createdAt: daysFromNow(55),
    updatedAt: daysFromNow(48),
    estimatedDelivery: daysFromNow(48),
  },
  {
    id: "order-027",
    orderNumber: "ORD-2026-0524",
    customerId: "cust-006",
    customerName: "Tyler Russo",
    customerEmail: "tyler.russo@hotmail.com",
    items: [
      { productId: "prod-021", productName: "Heritage Leather Bifold Wallet", productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", quantity: 1, price: 89.99, selectedVariants: { "Leather Color": "Dark Brown" } },
      { productId: "prod-028", productName: "Titanium Carabiner Keychain", productImage: "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80", quantity: 1, price: 39.99, selectedVariants: { Finish: "Black PVD" } },
    ],
    shippingAddress: { fullName: "Tyler Russo", email: "tyler.russo@hotmail.com", phone: "773-441-9920", address1: "3302 N Lincoln Ave", city: "Chicago", state: "IL", zip: "60657", country: "United States" },
    subtotal: 129.98,
    shipping: 0,
    tax: 11.70,
    total: 141.68,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(58), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(57, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(55), note: "Package shipped via USPS First Class" },
      { status: "delivered", date: daysFromNow(52), note: "Package delivered" },
    ],
    createdAt: daysFromNow(58),
    updatedAt: daysFromNow(52),
    estimatedDelivery: daysFromNow(52),
  },
  {
    id: "order-028",
    orderNumber: "ORD-2026-0523",
    customerId: "cust-009",
    customerName: "Rachel Kim",
    customerEmail: "rachel.kim@yahoo.com",
    items: [
      { productId: "prod-023", productName: "Luxury Cashmere Scarf", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 119.99, selectedVariants: { Color: "Ivory" } },
    ],
    shippingAddress: { fullName: "Rachel Kim", email: "rachel.kim@yahoo.com", phone: "212-883-4410", address1: "245 E 93rd Street", address2: "Apt 12A", city: "New York", state: "NY", zip: "10128", country: "United States" },
    subtotal: 119.99,
    shipping: 0,
    tax: 10.70,
    total: 130.69,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(60), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(59, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(57), note: "Package shipped via USPS Priority" },
      { status: "delivered", date: daysFromNow(54), note: "Package delivered" },
    ],
    createdAt: daysFromNow(60),
    updatedAt: daysFromNow(54),
    estimatedDelivery: daysFromNow(54),
  },
  {
    id: "order-029",
    orderNumber: "ORD-2026-0522",
    customerId: "cust-010",
    customerName: "Brian Okonkwo",
    customerEmail: "brian.okonkwo@gmail.com",
    items: [
      { productId: "prod-018", productName: "FlexCore Yoga Mat Pro", productImage: "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80", quantity: 1, price: 79.99, selectedVariants: { Color: "Obsidian Black" } },
    ],
    shippingAddress: { fullName: "Brian Okonkwo", email: "brian.okonkwo@gmail.com", phone: "614-772-3388", address1: "5511 Olentangy River Rd", city: "Columbus", state: "OH", zip: "43235", country: "United States" },
    subtotal: 79.99,
    shipping: 0,
    tax: 7.20,
    total: 87.19,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(65), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(64, 4), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(62), note: "Package shipped via UPS" },
      { status: "delivered", date: daysFromNow(59), note: "Package delivered" },
    ],
    createdAt: daysFromNow(65),
    updatedAt: daysFromNow(59),
    estimatedDelivery: daysFromNow(59),
  },
  {
    id: "order-030",
    orderNumber: "ORD-2026-0521",
    customerId: "cust-007",
    customerName: "Alicia Fontaine",
    customerEmail: "alicia.fontaine@gmail.com",
    items: [
      { productId: "prod-015", productName: "Ceramic Diffuser & Oil Set", productImage: "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80", quantity: 2, price: 79.99, selectedVariants: { "Ceramic Glaze": "Midnight Blue" } },
    ],
    shippingAddress: { fullName: "Alicia Fontaine", email: "alicia.fontaine@gmail.com", phone: "504-228-1144", address1: "719 Magazine Street", city: "New Orleans", state: "LA", zip: "70130", country: "United States" },
    subtotal: 159.98,
    shipping: 0,
    tax: 14.40,
    total: 174.38,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(70), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(69, 5), note: "Payment confirmed, preparing your order" },
      { status: "shipped", date: daysFromNow(67), note: "Package shipped via USPS Priority" },
      { status: "delivered", date: daysFromNow(64), note: "Package delivered" },
    ],
    createdAt: daysFromNow(70),
    updatedAt: daysFromNow(64),
    estimatedDelivery: daysFromNow(64),
  },
  // ── More orders spreading across 90 days ──────────────────────────────────
  {
    id: "order-031",
    orderNumber: "ORD-2026-0520",
    customerId: "cust-011",
    customerName: "Lauren McAllister",
    customerEmail: "lauren.mac@email.com",
    items: [
      { productId: "prod-010", productName: "Essential Organic Tee 3-Pack", productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80", quantity: 3, price: 59.99, selectedVariants: { Size: "M", "Color Pack": "Neutrals" } },
    ],
    shippingAddress: { fullName: "Lauren McAllister", email: "lauren.mac@email.com", phone: "503-774-2291", address1: "1847 NW Thurman Street", city: "Portland", state: "OR", zip: "97209", country: "United States" },
    subtotal: 179.97,
    shipping: 0,
    tax: 16.20,
    total: 196.17,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(72), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(71, 6), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(69), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(66), note: "Package delivered" },
    ],
    createdAt: daysFromNow(72),
    updatedAt: daysFromNow(66),
    estimatedDelivery: daysFromNow(66),
  },
  {
    id: "order-032",
    orderNumber: "ORD-2026-0519",
    customerId: "cust-012",
    customerName: "Kevin Tran",
    customerEmail: "kevintran@fastmail.com",
    items: [
      { productId: "prod-025", productName: "Polarized Aviator Sunglasses", productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", quantity: 1, price: 149.99, selectedVariants: { "Frame Color": "Silver/Gray" } },
    ],
    shippingAddress: { fullName: "Kevin Tran", email: "kevintran@fastmail.com", phone: "713-661-5520", address1: "2231 Westheimer Rd", city: "Houston", state: "TX", zip: "77098", country: "United States" },
    subtotal: 149.99,
    shipping: 0,
    tax: 12.37,
    total: 162.36,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(75), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(74, 4), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(72), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(69), note: "Package delivered" },
    ],
    createdAt: daysFromNow(75),
    updatedAt: daysFromNow(69),
    estimatedDelivery: daysFromNow(69),
  },
  {
    id: "order-033",
    orderNumber: "ORD-2026-0518",
    customerId: "cust-013",
    customerName: "Maria Delgado",
    customerEmail: "maria.delgado@icloud.com",
    items: [
      { productId: "prod-032", productName: "Resistance Band Training Set", productImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80", quantity: 1, price: 49.99, selectedVariants: { Color: "Gray/Blue" } },
    ],
    shippingAddress: { fullName: "Maria Delgado", email: "maria.delgado@icloud.com", phone: "720-533-8812", address1: "3901 W 38th Ave", city: "Denver", state: "CO", zip: "80212", country: "United States" },
    subtotal: 49.99,
    shipping: 5.99,
    tax: 4.50,
    total: 60.48,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(78), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(77, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(75), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(72), note: "Package delivered" },
    ],
    createdAt: daysFromNow(78),
    updatedAt: daysFromNow(72),
    estimatedDelivery: daysFromNow(72),
  },
  {
    id: "order-034",
    orderNumber: "ORD-2026-0517",
    customerId: "cust-014",
    customerName: "Steven Brooks",
    customerEmail: "s.brooks@corporatemail.net",
    items: [
      { productId: "prod-002", productName: "Apex Slim Laptop 15", productImage: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80", quantity: 1, price: 1299.99, selectedVariants: { Color: "Silver" } },
      { productId: "prod-001", productName: "SoundWave Pro X Wireless Headphones", productImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80", quantity: 1, price: 249.99, selectedVariants: { Color: "Midnight Black" } },
    ],
    shippingAddress: { fullName: "Steven Brooks", email: "s.brooks@corporatemail.net", phone: "602-447-3319", address1: "8920 E Pinnacle Peak Rd", city: "Scottsdale", state: "AZ", zip: "85255", country: "United States" },
    subtotal: 1549.98,
    shipping: 0,
    tax: 139.50,
    total: 1689.48,
    discount: 155.00,
    promoCode: "BUNDLE10",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(80), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(79, 3), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(77), note: "Package shipped via FedEx Priority Overnight" },
      { status: "delivered", date: daysFromNow(75), note: "Package delivered" },
    ],
    createdAt: daysFromNow(80),
    updatedAt: daysFromNow(75),
    estimatedDelivery: daysFromNow(75),
  },
  {
    id: "order-035",
    orderNumber: "ORD-2026-0516",
    customerId: "cust-015",
    customerName: "Natalie Webb",
    customerEmail: "natalie.webb@email.com",
    items: [
      { productId: "prod-007", productName: "Meridian Merino Crewneck Sweater", productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80", quantity: 1, price: 129.99, selectedVariants: { Size: "S", Color: "Navy" } },
    ],
    shippingAddress: { fullName: "Natalie Webb", email: "natalie.webb@email.com", phone: "305-448-7723", address1: "1900 Brickell Ave", address2: "Apt 22D", city: "Miami", state: "FL", zip: "33129", country: "United States" },
    subtotal: 129.99,
    shipping: 0,
    tax: 8.71,
    total: 138.70,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(83), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(82, 6), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(80), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(77), note: "Package delivered" },
    ],
    createdAt: daysFromNow(83),
    updatedAt: daysFromNow(77),
    estimatedDelivery: daysFromNow(77),
  },
  {
    id: "order-036",
    orderNumber: "ORD-2026-0515",
    customerId: "cust-016",
    customerName: "Thomas Nielsen",
    customerEmail: "thomas.n@gmail.com",
    items: [
      { productId: "prod-019", productName: "PowerLift Adjustable Dumbbells", productImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80", quantity: 1, price: 349.99, selectedVariants: {} },
    ],
    shippingAddress: { fullName: "Thomas Nielsen", email: "thomas.n@gmail.com", phone: "415-882-3311", address1: "2200 Fillmore Street", city: "San Francisco", state: "CA", zip: "94115", country: "United States" },
    subtotal: 349.99,
    shipping: 0,
    tax: 31.50,
    total: 381.49,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(85), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(84, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(82), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(79), note: "Package delivered" },
    ],
    createdAt: daysFromNow(85),
    updatedAt: daysFromNow(79),
    estimatedDelivery: daysFromNow(79),
  },
  {
    id: "order-037",
    orderNumber: "ORD-2026-0514",
    customerId: "cust-017",
    customerName: "Aisha Johnson",
    customerEmail: "aisha.j@protonmail.com",
    items: [
      { productId: "prod-011", productName: "Heritage Selvedge Denim Jeans", productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", quantity: 1, price: 195.00, selectedVariants: { "Waist x Inseam": "30x32", Wash: "Stone Wash" } },
    ],
    shippingAddress: { fullName: "Aisha Johnson", email: "aisha.j@protonmail.com", phone: "901-441-2290", address1: "655 Poplar Ave", city: "Memphis", state: "TN", zip: "38105", country: "United States" },
    subtotal: 195.00,
    shipping: 0,
    tax: 17.55,
    total: 212.55,
    discount: 0,
    status: "cancelled",
    paymentStatus: "refunded",
    timeline: [
      { status: "pending", date: daysFromNow(87), note: "Order placed successfully" },
      { status: "cancelled", date: daysFromNow(86, 8), note: "Order cancelled at customer request. Full refund issued." },
    ],
    createdAt: daysFromNow(87),
    updatedAt: daysFromNow(86, 8),
    estimatedDelivery: daysFromNow(82),
  },
  {
    id: "order-038",
    orderNumber: "ORD-2026-0513",
    customerId: "cust-018",
    customerName: "Colin Murphy",
    customerEmail: "colin.murphy@me.com",
    items: [
      { productId: "prod-013", productName: "Artisan Pour-Over Coffee Station", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 1, price: 149.99, selectedVariants: { "Wood Finish": "White Oak" } },
    ],
    shippingAddress: { fullName: "Colin Murphy", email: "colin.murphy@me.com", phone: "612-558-4430", address1: "2801 Lyndale Ave S", city: "Minneapolis", state: "MN", zip: "55408", country: "United States" },
    subtotal: 149.99,
    shipping: 0,
    tax: 12.00,
    total: 161.99,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(88), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(87, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(85), note: "Package shipped via UPS" },
      { status: "delivered", date: daysFromNow(82), note: "Package delivered" },
    ],
    createdAt: daysFromNow(88),
    updatedAt: daysFromNow(82),
    estimatedDelivery: daysFromNow(82),
  },
  {
    id: "order-039",
    orderNumber: "ORD-2026-0512",
    customerId: "cust-019",
    customerName: "Diane Foster",
    customerEmail: "diane.foster@gmail.com",
    items: [
      { productId: "prod-016", productName: "Modular Bamboo Shelving System", productImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", quantity: 1, price: 229.99, selectedVariants: { Configuration: "3-Bay Linked" } },
    ],
    shippingAddress: { fullName: "Diane Foster", email: "diane.foster@gmail.com", phone: "303-228-9901", address1: "1710 Wazee Street", city: "Denver", state: "CO", zip: "80202", country: "United States" },
    subtotal: 229.99,
    shipping: 0,
    tax: 19.55,
    total: 249.54,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(89), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(88, 4), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(86), note: "Package shipped via FedEx" },
      { status: "delivered", date: daysFromNow(83), note: "Package delivered" },
    ],
    createdAt: daysFromNow(89),
    updatedAt: daysFromNow(83),
    estimatedDelivery: daysFromNow(83),
  },
  {
    id: "order-040",
    orderNumber: "ORD-2026-0511",
    customerId: "cust-020",
    customerName: "Marcus Hill",
    customerEmail: "marcus.hill@email.net",
    items: [
      { productId: "prod-022", productName: "Navigator Canvas Backpack", productImage: "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80", quantity: 1, price: 179.99, selectedVariants: { Color: "Waxed Olive" } },
    ],
    shippingAddress: { fullName: "Marcus Hill", email: "marcus.hill@email.net", phone: "615-334-8823", address1: "420 Church Street", address2: "Unit 5A", city: "Nashville", state: "TN", zip: "37219", country: "United States" },
    subtotal: 179.99,
    shipping: 0,
    tax: 16.20,
    total: 196.19,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(90), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(89, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(87), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(84), note: "Package delivered" },
    ],
    createdAt: daysFromNow(90),
    updatedAt: daysFromNow(84),
    estimatedDelivery: daysFromNow(84),
  },
  {
    id: "order-041",
    orderNumber: "ORD-2026-0510",
    customerId: "cust-021",
    customerName: "Simone Laurent",
    customerEmail: "simone.l@outlook.com",
    items: [
      { productId: "prod-024", productName: "Minimal Steel Mesh Watch", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 179.99, selectedVariants: { "Dial Color": "Champagne" } },
    ],
    shippingAddress: { fullName: "Simone Laurent", email: "simone.l@outlook.com", phone: "617-923-4415", address1: "88 Marlborough Street", city: "Boston", state: "MA", zip: "02116", country: "United States" },
    subtotal: 179.99,
    shipping: 0,
    tax: 16.20,
    total: 196.19,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(62), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(61, 4), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(59), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(56), note: "Package delivered" },
    ],
    createdAt: daysFromNow(62),
    updatedAt: daysFromNow(56),
    estimatedDelivery: daysFromNow(56),
  },
  {
    id: "order-042",
    orderNumber: "ORD-2026-0509",
    customerId: "cust-022",
    customerName: "Jason Rivera",
    customerEmail: "jrivera@yahoo.com",
    items: [
      { productId: "prod-004", productName: "NovaPad Ultra Tablet 11", productImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80", quantity: 1, price: 479.99, selectedVariants: { Color: "Frost Blue" } },
    ],
    shippingAddress: { fullName: "Jason Rivera", email: "jrivera@yahoo.com", phone: "787-229-5510", address1: "1503 Ashford Ave", city: "San Juan", state: "PR", zip: "00911", country: "United States" },
    subtotal: 479.99,
    shipping: 9.99,
    tax: 43.20,
    total: 533.18,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(47), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(46, 4), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(44), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(41), note: "Package delivered" },
    ],
    createdAt: daysFromNow(47),
    updatedAt: daysFromNow(41),
    estimatedDelivery: daysFromNow(41),
  },
  {
    id: "order-043",
    orderNumber: "ORD-2026-0508",
    customerId: "cust-002",
    customerName: "James Whitfield",
    customerEmail: "j.whitfield@promail.com",
    items: [
      { productId: "prod-008", productName: "Altitude Waterproof Shell Jacket", productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80", quantity: 1, price: 289.99, selectedVariants: { Size: "L", Color: "Midnight Navy" } },
    ],
    shippingAddress: { fullName: "James Whitfield", email: "j.whitfield@promail.com", phone: "617-555-0192", address1: "104 Commonwealth Ave", address2: "Apt 3B", city: "Boston", state: "MA", zip: "02116", country: "United States" },
    subtotal: 289.99,
    shipping: 0,
    tax: 23.93,
    total: 313.92,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(43), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(42, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(40), note: "Package shipped via FedEx" },
      { status: "delivered", date: daysFromNow(37), note: "Package delivered" },
    ],
    createdAt: daysFromNow(43),
    updatedAt: daysFromNow(37),
    estimatedDelivery: daysFromNow(37),
  },
  {
    id: "order-044",
    orderNumber: "ORD-2026-0507",
    customerId: "cust-008",
    customerName: "David Park",
    customerEmail: "dpark@workmail.com",
    items: [
      { productId: "prod-006", productName: "PixelFrame Digital Art Display", productImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80", quantity: 1, price: 399.99, selectedVariants: { "Frame Finish": "Matte Black" } },
    ],
    shippingAddress: { fullName: "David Park", email: "dpark@workmail.com", phone: "310-558-6672", address1: "8901 Wilshire Blvd", address2: "Penthouse 4", city: "Beverly Hills", state: "CA", zip: "90210", country: "United States" },
    subtotal: 399.99,
    shipping: 0,
    tax: 36.00,
    total: 435.99,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(52), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(51, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(49), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(46), note: "Package delivered" },
    ],
    createdAt: daysFromNow(52),
    updatedAt: daysFromNow(46),
    estimatedDelivery: daysFromNow(46),
  },
  {
    id: "order-045",
    orderNumber: "ORD-2026-0506",
    customerId: "cust-001",
    customerName: "Emma Rodriguez",
    customerEmail: "emma.rodriguez@email.com",
    items: [
      { productId: "prod-015", productName: "Ceramic Diffuser & Oil Set", productImage: "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80", quantity: 1, price: 79.99, selectedVariants: { "Ceramic Glaze": "Speckled Cream" } },
    ],
    shippingAddress: { fullName: "Emma Rodriguez", email: "emma.rodriguez@email.com", phone: "512-334-7821", address1: "2847 Lavender Lane", city: "Austin", state: "TX", zip: "78704", country: "United States" },
    subtotal: 79.99,
    shipping: 0,
    tax: 6.60,
    total: 86.59,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(68), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(67, 4), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(65), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(62), note: "Package delivered" },
    ],
    createdAt: daysFromNow(68),
    updatedAt: daysFromNow(62),
    estimatedDelivery: daysFromNow(62),
  },
  {
    id: "order-046",
    orderNumber: "ORD-2026-0505",
    customerId: "cust-009",
    customerName: "Rachel Kim",
    customerEmail: "rachel.kim@yahoo.com",
    items: [
      { productId: "prod-021", productName: "Heritage Leather Bifold Wallet", productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", quantity: 1, price: 89.99, selectedVariants: { "Leather Color": "Chestnut" } },
    ],
    shippingAddress: { fullName: "Rachel Kim", email: "rachel.kim@yahoo.com", phone: "212-883-4410", address1: "245 E 93rd Street", address2: "Apt 12A", city: "New York", state: "NY", zip: "10128", country: "United States" },
    subtotal: 89.99,
    shipping: 0,
    tax: 8.01,
    total: 98.00,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(73), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(72, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(70), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(67), note: "Package delivered" },
    ],
    createdAt: daysFromNow(73),
    updatedAt: daysFromNow(67),
    estimatedDelivery: daysFromNow(67),
  },
  {
    id: "order-047",
    orderNumber: "ORD-2026-0504",
    customerId: "cust-020",
    customerName: "Marcus Hill",
    customerEmail: "marcus.hill@email.net",
    items: [
      { productId: "prod-003", productName: "VisionCam 4K Action Camera", productImage: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80", quantity: 1, price: 349.99, selectedVariants: { Color: "Arctic White" } },
    ],
    shippingAddress: { fullName: "Marcus Hill", email: "marcus.hill@email.net", phone: "615-334-8823", address1: "420 Church Street", address2: "Unit 5A", city: "Nashville", state: "TN", zip: "37219", country: "United States" },
    subtotal: 349.99,
    shipping: 0,
    tax: 31.50,
    total: 381.49,
    discount: 0,
    status: "pending",
    paymentStatus: "unpaid",
    timeline: [
      { status: "pending", date: daysFromNow(0, -1), note: "Order placed, awaiting payment" },
    ],
    createdAt: daysFromNow(0, -1),
    updatedAt: daysFromNow(0, -1),
    estimatedDelivery: futureDate(7),
  },
  {
    id: "order-048",
    orderNumber: "ORD-2026-0503",
    customerId: "cust-019",
    customerName: "Diane Foster",
    customerEmail: "diane.foster@gmail.com",
    items: [
      { productId: "prod-031", productName: "Bamboo Cutting Board Set", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 2, price: 69.99, selectedVariants: {} },
    ],
    shippingAddress: { fullName: "Diane Foster", email: "diane.foster@gmail.com", phone: "303-228-9901", address1: "1710 Wazee Street", city: "Denver", state: "CO", zip: "80202", country: "United States" },
    subtotal: 139.98,
    shipping: 0,
    tax: 11.90,
    total: 151.88,
    discount: 0,
    status: "processing",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(3, -2), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(2, 6), note: "Payment confirmed, preparing your order" },
    ],
    createdAt: daysFromNow(3, -2),
    updatedAt: daysFromNow(2, 6),
    estimatedDelivery: futureDate(4),
  },
  {
    id: "order-049",
    orderNumber: "ORD-2026-0502",
    customerId: "cust-016",
    customerName: "Thomas Nielsen",
    customerEmail: "thomas.n@gmail.com",
    items: [
      { productId: "prod-017", productName: "TrailBlazer Carbon Trekking Poles", productImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80", quantity: 1, price: 119.99, selectedVariants: { Color: "Carbon Black" } },
      { productId: "prod-020", productName: "Aero Road Cycling Helmet", productImage: "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80", quantity: 1, price: 189.99, selectedVariants: { Size: "L (58-62 cm)", Color: "Gloss White" } },
    ],
    shippingAddress: { fullName: "Thomas Nielsen", email: "thomas.n@gmail.com", phone: "415-882-3311", address1: "2200 Fillmore Street", city: "San Francisco", state: "CA", zip: "94115", country: "United States" },
    subtotal: 309.98,
    shipping: 0,
    tax: 27.90,
    total: 337.88,
    discount: 0,
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(4, -3), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(3, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(2), note: "Package shipped via FedEx" },
    ],
    createdAt: daysFromNow(4, -3),
    updatedAt: daysFromNow(2),
    estimatedDelivery: futureDate(2),
  },
  {
    id: "order-050",
    orderNumber: "ORD-2026-0501",
    customerId: "cust-022",
    customerName: "Jason Rivera",
    customerEmail: "jrivera@yahoo.com",
    items: [
      { productId: "prod-010", productName: "Essential Organic Tee 3-Pack", productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80", quantity: 2, price: 59.99, selectedVariants: { Size: "M", "Color Pack": "Blues" } },
      { productId: "prod-009", productName: "Linen Relaxed Chino Trousers", productImage: "https://images.unsplash.com/photo-1594938298603-f8a3d0040133?w=800&q=80", quantity: 1, price: 89.99, selectedVariants: { Size: "32", Color: "Pale Blue" } },
    ],
    shippingAddress: { fullName: "Jason Rivera", email: "jrivera@yahoo.com", phone: "787-229-5510", address1: "1503 Ashford Ave", city: "San Juan", state: "PR", zip: "00911", country: "United States" },
    subtotal: 209.97,
    shipping: 9.99,
    tax: 18.90,
    total: 238.86,
    discount: 21.00,
    promoCode: "SUMMER10",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(28), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(27, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(25), note: "Package shipped via USPS Priority Mail" },
      { status: "delivered", date: daysFromNow(22), note: "Package delivered" },
    ],
    createdAt: daysFromNow(28),
    updatedAt: daysFromNow(22),
    estimatedDelivery: daysFromNow(22),
  },
  {
    id: "order-051",
    orderNumber: "ORD-2026-0500",
    customerId: "cust-005",
    customerName: "Sarah Okafor",
    customerEmail: "sarah.okafor@icloud.com",
    items: [
      { productId: "prod-026", productName: "Compact Espresso Machine", productImage: "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80", quantity: 1, price: 399.99, selectedVariants: { Color: "Matte Black" } },
    ],
    shippingAddress: { fullName: "Sarah Okafor", email: "sarah.okafor@icloud.com", phone: "404-887-5521", address1: "1200 Peachtree St NE", address2: "Apt 8F", city: "Atlanta", state: "GA", zip: "30309", country: "United States" },
    subtotal: 399.99,
    shipping: 0,
    tax: 26.80,
    total: 426.79,
    discount: 0,
    status: "processing",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(1, -4), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(0, -7), note: "Payment confirmed, preparing your order" },
    ],
    createdAt: daysFromNow(1, -4),
    updatedAt: daysFromNow(0, -7),
    estimatedDelivery: futureDate(5),
  },
  {
    id: "order-052",
    orderNumber: "ORD-2026-0499",
    customerId: "cust-011",
    customerName: "Lauren McAllister",
    customerEmail: "lauren.mac@email.com",
    items: [
      { productId: "prod-014", productName: "Boucle Accent Armchair", productImage: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80", quantity: 1, price: 649.99, selectedVariants: { "Fabric Color": "Sage Green" } },
    ],
    shippingAddress: { fullName: "Lauren McAllister", email: "lauren.mac@email.com", phone: "503-774-2291", address1: "1847 NW Thurman Street", city: "Portland", state: "OR", zip: "97209", country: "United States" },
    subtotal: 649.99,
    shipping: 19.99,
    tax: 58.50,
    total: 728.48,
    discount: 65.00,
    promoCode: "VIP10",
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(32), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(31, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(29), note: "Package shipped via freight service" },
      { status: "delivered", date: daysFromNow(25), note: "Delivered and assembled" },
    ],
    createdAt: daysFromNow(32),
    updatedAt: daysFromNow(25),
    estimatedDelivery: daysFromNow(25),
  },
  {
    id: "order-053",
    orderNumber: "ORD-2026-0498",
    customerId: "cust-013",
    customerName: "Maria Delgado",
    customerEmail: "maria.delgado@icloud.com",
    items: [
      { productId: "prod-005", productName: "PulseWatch GT Smartwatch", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 299.99, selectedVariants: { "Band Color": "Olive Green" } },
    ],
    shippingAddress: { fullName: "Maria Delgado", email: "maria.delgado@icloud.com", phone: "720-533-8812", address1: "3901 W 38th Ave", city: "Denver", state: "CO", zip: "80212", country: "United States" },
    subtotal: 299.99,
    shipping: 0,
    tax: 25.50,
    total: 325.49,
    discount: 0,
    status: "delivered",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(38), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(37, 5), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(35), note: "Package shipped" },
      { status: "delivered", date: daysFromNow(32), note: "Package delivered" },
    ],
    createdAt: daysFromNow(38),
    updatedAt: daysFromNow(32),
    estimatedDelivery: daysFromNow(32),
  },
  {
    id: "order-054",
    orderNumber: "ORD-2026-0497",
    customerId: "cust-017",
    customerName: "Aisha Johnson",
    customerEmail: "aisha.j@protonmail.com",
    items: [
      { productId: "prod-023", productName: "Luxury Cashmere Scarf", productImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80", quantity: 1, price: 119.99, selectedVariants: { Color: "Burgundy" } },
      { productId: "prod-025", productName: "Polarized Aviator Sunglasses", productImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80", quantity: 1, price: 149.99, selectedVariants: { "Frame Color": "Gunmetal/Green" } },
    ],
    shippingAddress: { fullName: "Aisha Johnson", email: "aisha.j@protonmail.com", phone: "901-441-2290", address1: "655 Poplar Ave", city: "Memphis", state: "TN", zip: "38105", country: "United States" },
    subtotal: 269.98,
    shipping: 0,
    tax: 24.30,
    total: 294.28,
    discount: 0,
    status: "shipped",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(5, -2), note: "Order placed successfully" },
      { status: "processing", date: daysFromNow(4, 6), note: "Payment confirmed" },
      { status: "shipped", date: daysFromNow(3, 2), note: "Package shipped via UPS — Tracking: 1ZA9B8C7D6E5F4G3" },
    ],
    createdAt: daysFromNow(5, -2),
    updatedAt: daysFromNow(3, 2),
    estimatedDelivery: futureDate(2),
  },
  {
    id: "order-055",
    orderNumber: "ORD-2026-0496",
    customerId: "cust-018",
    customerName: "Colin Murphy",
    customerEmail: "colin.murphy@me.com",
    items: [
      { productId: "prod-028", productName: "Titanium Carabiner Keychain", productImage: "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80", quantity: 3, price: 39.99, selectedVariants: { Finish: "Blue Anodized" } },
    ],
    shippingAddress: { fullName: "Colin Murphy", email: "colin.murphy@me.com", phone: "612-558-4430", address1: "2801 Lyndale Ave S", city: "Minneapolis", state: "MN", zip: "55408", country: "United States" },
    subtotal: 119.97,
    shipping: 0,
    tax: 9.60,
    total: 129.57,
    discount: 0,
    status: "pending",
    paymentStatus: "paid",
    timeline: [
      { status: "pending", date: daysFromNow(0, -3), note: "Order placed successfully" },
    ],
    createdAt: daysFromNow(0, -3),
    updatedAt: daysFromNow(0, -3),
    estimatedDelivery: futureDate(5),
  },
]
