import type { Product } from "@/types"

export const PRODUCTS: Product[] = [
  // ── Electronics ────────────────────────────────────────────────────────────
  {
    id: "prod-001",
    name: "SoundWave Pro X Wireless Headphones",
    slug: "soundwave-pro-x-wireless-headphones",
    description: "Premium noise-cancelling headphones with 40-hour battery life and studio-quality sound.",
    longDescription:
      "The SoundWave Pro X redefines what wireless headphones can be. Built with 40mm custom-tuned drivers and our proprietary ANC technology, every listening session becomes an immersive experience. The adaptive noise cancellation adjusts in real time to your environment — whether you're on a noisy commute or in a quiet library. With up to 40 hours of playback on a single charge and fast-charge support that gives you 5 hours of listening in just 10 minutes, you'll never be without your music. The plush memory-foam ear cushions and adjustable headband ensure comfort through even the longest sessions.",
    price: 249.99,
    compareAtPrice: 319.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 312,
    reviews: [
      {
        id: "rev-001-1",
        author: "Marcus T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
        rating: 5,
        date: "2026-03-10",
        comment: "Best headphones I've ever owned. The noise cancellation is phenomenal on my daily commute.",
        verified: true,
      },
      {
        id: "rev-001-2",
        author: "Priya S.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
        rating: 5,
        date: "2026-02-28",
        comment: "40-hour battery is no joke. I charged these on Monday and they're still going on Friday.",
        verified: true,
      },
      {
        id: "rev-001-3",
        author: "Derek W.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Derek",
        rating: 4,
        date: "2026-02-15",
        comment: "Great sound and comfort. The app could use some polish but the headphones themselves are excellent.",
        verified: false,
      },
      {
        id: "rev-001-4",
        author: "Amelia R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia",
        rating: 5,
        date: "2026-01-30",
        comment: "Bought these for long-haul flights. Absolute game changer. I could barely hear the engines.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Midnight Black", "Pearl White", "Navy Blue"] },
    ],
    stock: 87,
    status: "active",
    tags: ["headphones", "wireless", "noise-cancelling", "audio", "bluetooth"],
    createdAt: "2025-11-01T08:00:00Z",
  },
  {
    id: "prod-002",
    name: "Apex Slim Laptop 15",
    slug: "apex-slim-laptop-15",
    description: "Ultra-thin 15-inch laptop with OLED display, 12-core processor, and all-day battery life.",
    longDescription:
      "The Apex Slim 15 packs desktop-class performance into a chassis that weighs just 1.2 kg. Its 15.6-inch 3K OLED display delivers breathtaking color accuracy with 100% DCI-P3 coverage — perfect for creative professionals who demand precision. Powered by the latest 12-core processor and up to 32 GB of LPDDR5 RAM, it handles video editing, 3D rendering, and multitasking with ease. The MagSafe-style 140 W charger refills the 75 Wh battery in under an hour, while normal use stretches well past 12 hours. A full-sized backlit keyboard and Thunderbolt 4 ports round out an impressive package.",
    price: 1299.99,
    compareAtPrice: 1499.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 178,
    reviews: [
      {
        id: "rev-002-1",
        author: "Kenji O.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kenji",
        rating: 5,
        date: "2026-03-18",
        comment: "The OLED screen is stunning. Night and day difference from my old laptop.",
        verified: true,
      },
      {
        id: "rev-002-2",
        author: "Rachel M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel",
        rating: 4,
        date: "2026-03-05",
        comment: "Super light and fast. The fan can get loud under heavy load but otherwise it's perfect.",
        verified: true,
      },
      {
        id: "rev-002-3",
        author: "Tom B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tom",
        rating: 5,
        date: "2026-02-20",
        comment: "My go-to machine for video editing. Renders faster than my old desktop.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Space Gray", "Silver"] },
    ],
    stock: 34,
    status: "active",
    tags: ["laptop", "ultrabook", "OLED", "portable", "productivity"],
    createdAt: "2025-10-15T08:00:00Z",
  },
  {
    id: "prod-003",
    name: "VisionCam 4K Action Camera",
    slug: "visioncam-4k-action-camera",
    description: "Rugged 4K action camera with 3-axis stabilization, waterproof to 33 ft, and 2-inch touchscreen.",
    longDescription:
      "The VisionCam 4K is built to go wherever you do. Encased in a military-grade housing, it records crisp 4K/60fps footage while its 3-axis HyperSmooth stabilization eliminates shake on the gnarliest trails. The 2-inch front-facing touchscreen makes framing selfie shots effortless. With a 1400 mAh battery delivering up to 2 hours of 4K recording and a modular accessory ecosystem that includes mounts for helmets, bikes, and surfboards, it's the only action camera you'll ever need.",
    price: 349.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
      "https://images.unsplash.com/photo-1498049794991-d7b9ac80a08f?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 94,
    reviews: [
      {
        id: "rev-003-1",
        author: "Sofia L.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
        rating: 5,
        date: "2026-03-22",
        comment: "Took this surfing and the footage was incredible. Zero water damage after 2 hours in the ocean.",
        verified: true,
      },
      {
        id: "rev-003-2",
        author: "Dan H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dan",
        rating: 4,
        date: "2026-02-12",
        comment: "Stabilization is really impressive for the price. Battery life is on the shorter side though.",
        verified: true,
      },
      {
        id: "rev-003-3",
        author: "Nina P.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nina",
        rating: 5,
        date: "2026-01-28",
        comment: "Crystal clear 4K footage on ski slopes. The color grading out of camera is great too.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Stealth Black", "Arctic White"] },
    ],
    stock: 52,
    status: "active",
    tags: ["camera", "action-camera", "4K", "waterproof", "outdoor"],
    createdAt: "2025-09-20T08:00:00Z",
  },
  {
    id: "prod-004",
    name: "NovaPad Ultra Tablet 11",
    slug: "novapad-ultra-tablet-11",
    description: "11-inch 120 Hz AMOLED tablet with stylus support, 8 GB RAM, and quad speakers.",
    longDescription:
      "The NovaPad Ultra 11 blurs the line between tablet and laptop. Its 11-inch AMOLED display refreshes at 120 Hz for silky-smooth scrolling and low-latency stylus input that feels like pen on paper. With 8 GB of RAM and 256 GB of fast UFS storage, even demanding creative apps launch instantly. The quad-speaker array with Dolby Atmos tuning turns movie night into a genuine cinematic experience. Whether you're sketching, note-taking, or streaming, the 8200 mAh battery keeps pace with a full workday.",
    price: 479.99,
    compareAtPrice: 549.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
      "https://images.unsplash.com/photo-1498049794991-d7b9ac80a08f?w=800&q=80",
    ],
    rating: 4.4,
    reviewCount: 143,
    reviews: [
      {
        id: "rev-004-1",
        author: "Lena K.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lena",
        rating: 5,
        date: "2026-03-14",
        comment: "The display is gorgeous. I use it daily for illustration work and the stylus lag is nearly zero.",
        verified: true,
      },
      {
        id: "rev-004-2",
        author: "Jordan F.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
        rating: 4,
        date: "2026-02-25",
        comment: "Bought as a secondary screen setup. Works great but the keyboard cover is sold separately.",
        verified: true,
      },
      {
        id: "rev-004-3",
        author: "Mike C.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
        rating: 4,
        date: "2026-02-08",
        comment: "Great for streaming. The speakers are surprisingly loud and clear for a tablet.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Graphite", "Champagne Gold", "Frost Blue"] },
    ],
    stock: 61,
    status: "active",
    tags: ["tablet", "AMOLED", "stylus", "portable", "entertainment"],
    createdAt: "2025-10-01T08:00:00Z",
  },
  {
    id: "prod-005",
    name: "PulseWatch GT Smartwatch",
    slug: "pulsewatch-gt-smartwatch",
    description: "Advanced health-tracking smartwatch with ECG, SpO2, GPS, and 7-day battery.",
    longDescription:
      "The PulseWatch GT is your 24/7 wellness companion. Medical-grade ECG and SpO2 sensors deliver clinically relevant heart health data straight to your wrist, while continuous stress monitoring and sleep stage tracking give you a full picture of your wellbeing. The always-on AMOLED display looks stunning in sunlight, and the built-in multi-band GPS locks on in seconds for accurate pace and route data. Best of all, the optimized processor stretches battery life to an impressive 7 days — so you only charge it on weekends.",
    price: 299.99,
    compareAtPrice: 349.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      "https://images.unsplash.com/photo-1498049794991-d7b9ac80a08f?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 267,
    reviews: [
      {
        id: "rev-005-1",
        author: "Carlos V.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
        rating: 5,
        date: "2026-03-20",
        comment: "ECG readings match my doctor's equipment almost perfectly. Worth every penny for the peace of mind.",
        verified: true,
      },
      {
        id: "rev-005-2",
        author: "Hailey N.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hailey",
        rating: 5,
        date: "2026-03-01",
        comment: "Sleep tracking finally helped me understand why I was always tired. 7-day battery is real.",
        verified: true,
      },
      {
        id: "rev-005-3",
        author: "Ahmed Z.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed",
        rating: 4,
        date: "2026-02-10",
        comment: "GPS is fast and accurate. Great running companion. Watch face customization could be wider.",
        verified: false,
      },
      {
        id: "rev-005-4",
        author: "Beth A.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Beth",
        rating: 5,
        date: "2026-01-22",
        comment: "Replaced my last three fitness trackers with this one. It does everything and more.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Band Color", values: ["Black", "Olive Green", "Blush Pink", "Slate Blue"] },
    ],
    stock: 119,
    status: "active",
    tags: ["smartwatch", "fitness", "health", "GPS", "wearable"],
    createdAt: "2025-08-15T08:00:00Z",
  },
  {
    id: "prod-006",
    name: "PixelFrame Digital Art Display",
    slug: "pixelframe-digital-art-display",
    description: "27-inch 4K digital canvas that displays your photo and art collections with gallery-quality precision.",
    longDescription:
      "The PixelFrame turns any wall into a living gallery. Its 27-inch IPS panel renders 4K resolution with a matte anti-glare coating that mimics real canvas texture under any lighting. An ambient light sensor automatically adjusts brightness to match the room, making digital photos look indistinguishable from prints. The companion app integrates with Google Photos, iCloud, Instagram, and 12 other services so your entire visual library is always within reach. The slim 8 mm aluminum frame comes in four finishes to complement any interior.",
    price: 399.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80",
    ],
    rating: 4.3,
    reviewCount: 88,
    reviews: [
      {
        id: "rev-006-1",
        author: "Sarah G.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
        rating: 5,
        date: "2026-03-15",
        comment: "My wedding photos look like actual prints on this thing. Guests always ask about it.",
        verified: true,
      },
      {
        id: "rev-006-2",
        author: "Paul T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Paul",
        rating: 4,
        date: "2026-02-18",
        comment: "Setup was painless. The iCloud integration works flawlessly.",
        verified: true,
      },
      {
        id: "rev-006-3",
        author: "Diana L.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diana",
        rating: 4,
        date: "2026-01-29",
        comment: "Beautiful piece of tech. Wish it had a built-in speaker for ambient soundscapes.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Frame Finish", values: ["Matte Black", "Brushed Aluminum", "Walnut Wood", "White"] },
    ],
    stock: 45,
    status: "active",
    tags: ["display", "digital-art", "home-decor", "photo", "4K"],
    createdAt: "2025-11-20T08:00:00Z",
  },

  // ── Clothing ────────────────────────────────────────────────────────────────
  {
    id: "prod-007",
    name: "Meridian Merino Crewneck Sweater",
    slug: "meridian-merino-crewneck-sweater",
    description: "Ethically sourced 100% Merino wool crewneck — naturally odor-resistant, temperature-regulating, and incredibly soft.",
    longDescription:
      "The Meridian Crewneck is crafted from 18.5-micron Merino wool sourced from certified responsible farms in New Zealand. Merino's natural crimp creates millions of tiny air pockets that trap warmth in winter and release heat in summer, making this the one sweater that truly works year-round. The fabric is naturally odor-resistant, so it stays fresh for multiple wears between washes. A classic fit with ribbed cuffs and hem gives it timeless versatility — dress it up over a collared shirt or wear it alone on weekends.",
    price: 129.99,
    compareAtPrice: 159.99,
    category: "Clothing",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 204,
    reviews: [
      {
        id: "rev-007-1",
        author: "Elena P.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
        rating: 5,
        date: "2026-03-12",
        comment: "Softest sweater I own. I have three now in different colors. No pilling after a year of wear.",
        verified: true,
      },
      {
        id: "rev-007-2",
        author: "Ryan J.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan",
        rating: 5,
        date: "2026-02-22",
        comment: "Wore this on a 3-week trip with minimal washing. The odor resistance is the real deal.",
        verified: true,
      },
      {
        id: "rev-007-3",
        author: "Grace H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace",
        rating: 5,
        date: "2026-02-05",
        comment: "Perfect weight — not too bulky, not too thin. Looks great tucked into high-waist trousers.",
        verified: true,
      },
      {
        id: "rev-007-4",
        author: "Caleb N.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Caleb",
        rating: 4,
        date: "2026-01-18",
        comment: "Quality is exceptional. Sizing runs slightly large — order one down if you're between sizes.",
        verified: false,
      },
    ],
    variants: [
      { type: "size", label: "Size", values: ["XS", "S", "M", "L", "XL", "XXL"] },
      { type: "color", label: "Color", values: ["Oatmeal", "Charcoal", "Forest Green", "Dusty Rose", "Navy"] },
    ],
    stock: 156,
    status: "active",
    tags: ["sweater", "merino", "wool", "sustainable", "classic"],
    createdAt: "2025-09-01T08:00:00Z",
  },
  {
    id: "prod-008",
    name: "Altitude Waterproof Shell Jacket",
    slug: "altitude-waterproof-shell-jacket",
    description: "3-layer Gore-Tex shell jacket that keeps you dry in any condition — packable to the size of a water bottle.",
    longDescription:
      "When the forecast is uncertain, the Altitude Shell has you covered. Its 3-layer Gore-Tex Pro membrane is guaranteed waterproof and breathable, preventing sweat buildup even on high-output hikes. Fully taped seams and a helmet-compatible hood with a single-hand adjustment ensure no water finds its way in. Despite its technical performance, the Altitude packs down into its own chest pocket — about the size of a 500 ml water bottle — making it easy to stash in any bag. YKK AquaGuard zippers and articulated patterning complete a jacket designed for real mountains.",
    price: 289.99,
    compareAtPrice: 349.99,
    category: "Clothing",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      "https://images.unsplash.com/photo-1556821840-3a63f4d732eb?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 139,
    reviews: [
      {
        id: "rev-008-1",
        author: "Luke M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luke",
        rating: 5,
        date: "2026-03-25",
        comment: "Hiked in heavy rain for 6 hours. Completely dry inside the whole time. Incredible jacket.",
        verified: true,
      },
      {
        id: "rev-008-2",
        author: "Isabelle D.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabelle",
        rating: 5,
        date: "2026-03-08",
        comment: "So packable I forget it's in my bag until I need it. Great to have on every trip.",
        verified: true,
      },
      {
        id: "rev-008-3",
        author: "Noah S.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Noah",
        rating: 4,
        date: "2026-02-16",
        comment: "Top-tier waterproofing. Runs a bit slim in the shoulders if you're broad-built.",
        verified: true,
      },
    ],
    variants: [
      { type: "size", label: "Size", values: ["XS", "S", "M", "L", "XL", "XXL"] },
      { type: "color", label: "Color", values: ["Alpine Red", "Midnight Navy", "Slate Gray", "Evergreen"] },
    ],
    stock: 73,
    status: "active",
    tags: ["jacket", "waterproof", "gore-tex", "hiking", "outdoor"],
    createdAt: "2025-08-20T08:00:00Z",
  },
  {
    id: "prod-009",
    name: "Linen Relaxed Chino Trousers",
    slug: "linen-relaxed-chino-trousers",
    description: "Lightweight Irish linen trousers with a relaxed cut and slightly tapered leg — summer's essential pant.",
    longDescription:
      "Made from 100% Irish linen, these trousers are the cool, breathable antidote to stuffy warm-weather dressing. The relaxed-through-hip fit transitions to a subtle taper below the knee for a silhouette that's effortlessly current. A flat front, side-seam pockets, and a back welt pocket keep the look clean, while the elastic half-waistband at the back makes these genuinely comfortable for all-day wear. Each pair is garment-washed for a lived-in texture that softens further with every wash.",
    price: 89.99,
    category: "Clothing",
    images: [
      "https://images.unsplash.com/photo-1594938298603-f8a3d0040133?w=800&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    ],
    rating: 4.4,
    reviewCount: 97,
    reviews: [
      {
        id: "rev-009-1",
        author: "Alice B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
        rating: 5,
        date: "2026-03-28",
        comment: "These are my new favorite warm-weather trousers. Lightweight, airy, and look sharp.",
        verified: true,
      },
      {
        id: "rev-009-2",
        author: "James W.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
        rating: 4,
        date: "2026-03-05",
        comment: "Love the linen quality. True to size and the taper is just right — not too skinny.",
        verified: true,
      },
      {
        id: "rev-009-3",
        author: "Olivia C.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia",
        rating: 4,
        date: "2026-02-19",
        comment: "Wore these in 95-degree heat with zero discomfort. The garment wash gives them great texture.",
        verified: false,
      },
    ],
    variants: [
      { type: "size", label: "Size", values: ["28", "30", "32", "34", "36", "38"] },
      { type: "color", label: "Color", values: ["Natural", "Sand", "Pale Blue", "Olive", "Black"] },
    ],
    stock: 104,
    status: "active",
    tags: ["trousers", "linen", "summer", "casual", "chinos"],
    createdAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-010",
    name: "Essential Organic Tee 3-Pack",
    slug: "essential-organic-tee-3-pack",
    description: "Three perfectly weighted GOTS-certified organic cotton crewneck tees in your choice of color combination.",
    longDescription:
      "The wardrobe staple, done right. Each tee is knit from 180 gsm GOTS-certified organic cotton — substantial enough to look structured but lightweight enough for hot days. Our seamless shoulder construction eliminates the boxy shoulder seam for a cleaner drape and better fit. The slightly longer back hem prevents untucking, and the reinforced neckline holds its shape wash after wash. Available in carefully curated color packs: Neutrals, Earth Tones, Blues, and Brights — so you can build a cohesive base layer wardrobe in one purchase.",
    price: 59.99,
    compareAtPrice: 74.99,
    category: "Clothing",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
      "https://images.unsplash.com/photo-1556821840-3a63f4d732eb?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 381,
    reviews: [
      {
        id: "rev-010-1",
        author: "Matt D.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Matt",
        rating: 5,
        date: "2026-03-30",
        comment: "I've rebought this 3-pack three times now. The quality is incredible for the price.",
        verified: true,
      },
      {
        id: "rev-010-2",
        author: "Chloe E.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe",
        rating: 5,
        date: "2026-03-12",
        comment: "The Earth Tones pack is perfect. These don't shrink or fade even after dozens of washes.",
        verified: true,
      },
      {
        id: "rev-010-3",
        author: "Victor O.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Victor",
        rating: 4,
        date: "2026-02-27",
        comment: "Great tees. The organic cotton is noticeably softer than conventional cotton.",
        verified: true,
      },
      {
        id: "rev-010-4",
        author: "Fiona M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fiona",
        rating: 5,
        date: "2026-02-03",
        comment: "Best value tees I've found. Bought the Neutrals pack — white, gray, and black. Wear them constantly.",
        verified: false,
      },
    ],
    variants: [
      { type: "size", label: "Size", values: ["XS", "S", "M", "L", "XL", "XXL"] },
      { type: "color", label: "Color Pack", values: ["Neutrals", "Earth Tones", "Blues", "Brights"] },
    ],
    stock: 230,
    status: "active",
    tags: ["t-shirt", "organic", "sustainable", "basics", "3-pack"],
    createdAt: "2025-07-10T08:00:00Z",
  },
  {
    id: "prod-011",
    name: "Heritage Selvedge Denim Jeans",
    slug: "heritage-selvedge-denim-jeans",
    description: "14 oz Japanese selvedge denim with a classic straight cut — jeans that improve with every wear.",
    longDescription:
      "Cut from 14 oz Japanese selvedge denim woven on vintage shuttle looms in Okayama, these jeans are built to last decades. The high-tension twill weave creates denim with a characteristic slub texture that fades beautifully with wear, developing unique personal creases over time. A classic straight leg and mid-rise sit work on most body types, and the five-pocket construction uses copper rivets at stress points for durability. Finished with a hidden coin pocket and raw cut hem for a clean look that you can cuff to your preferred length.",
    price: 195.00,
    compareAtPrice: 230.00,
    category: "Clothing",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 76,
    reviews: [
      {
        id: "rev-011-1",
        author: "Sam K.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam",
        rating: 5,
        date: "2026-03-20",
        comment: "These are the best jeans I've ever bought. Wore them every day for a year and they just get better.",
        verified: true,
      },
      {
        id: "rev-011-2",
        author: "Tessa R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tessa",
        rating: 5,
        date: "2026-03-02",
        comment: "The quality of Japanese selvedge is immediately apparent. Worth the investment.",
        verified: true,
      },
      {
        id: "rev-011-3",
        author: "Andrew L.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Andrew",
        rating: 5,
        date: "2026-02-11",
        comment: "Just received my second pair after 2 years with my first. Still perfect jeans.",
        verified: true,
      },
    ],
    variants: [
      { type: "size", label: "Waist x Inseam", values: ["28x30", "30x30", "30x32", "32x30", "32x32", "34x32", "36x32"] },
      { type: "color", label: "Wash", values: ["Raw Indigo", "One Wash", "Stone Wash"] },
    ],
    stock: 42,
    status: "active",
    tags: ["jeans", "denim", "selvedge", "japanese", "premium"],
    createdAt: "2025-10-05T08:00:00Z",
  },

  // ── Home & Living ──────────────────────────────────────────────────────────
  {
    id: "prod-012",
    name: "Sanctum Weighted Blanket",
    slug: "sanctum-weighted-blanket",
    description: "15 lb premium weighted blanket with glass bead filling, cooling cotton top, and minky plush underside.",
    longDescription:
      "The Sanctum Weighted Blanket uses deep-pressure stimulation to promote calm and improve sleep quality. The 15 lb weight is distributed evenly through a grid of micro-pockets filled with hypoallergenic glass beads — no shifting, no noise. The dual-sided construction pairs a cool, breathable 100% cotton top with a sumptuously soft minky plush underside, so you can flip it to suit the season. The removable, machine-washable cover keeps it fresh, and the premium inner is dry-clean safe. Available in 12 and 20 lb options to suit different body weights.",
    price: 119.99,
    compareAtPrice: 149.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 528,
    reviews: [
      {
        id: "rev-012-1",
        author: "Kim L.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kim",
        rating: 5,
        date: "2026-03-29",
        comment: "I fall asleep faster and sleep deeper with this blanket. My anxiety is noticeably reduced at night.",
        verified: true,
      },
      {
        id: "rev-012-2",
        author: "Eric S.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Eric",
        rating: 5,
        date: "2026-03-11",
        comment: "The beads are perfectly distributed — no lumpy spots. Washing the cover is easy too.",
        verified: true,
      },
      {
        id: "rev-012-3",
        author: "Mia F.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
        rating: 4,
        date: "2026-02-24",
        comment: "Great quality and the dual-sided fabric is a clever touch. Heavy to shake out but worth it.",
        verified: true,
      },
      {
        id: "rev-012-4",
        author: "Ben A.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ben",
        rating: 5,
        date: "2026-01-15",
        comment: "Bought one for each bed in the house. No one will give them up.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Slate Gray", "Ivory", "Dusty Blue", "Blush"] },
    ],
    stock: 182,
    status: "active",
    tags: ["blanket", "weighted", "sleep", "anxiety", "bedroom"],
    createdAt: "2025-06-01T08:00:00Z",
  },
  {
    id: "prod-013",
    name: "Artisan Pour-Over Coffee Station",
    slug: "artisan-pour-over-coffee-station",
    description: "Handcrafted walnut and stainless-steel pour-over station with gooseneck kettle and double-walled dripper.",
    longDescription:
      "For the coffee enthusiast who takes their morning ritual seriously, the Artisan Pour-Over Station elevates both the process and the aesthetic. The hand-finished solid walnut base holds a precision gooseneck kettle with built-in thermometer, a borosilicate glass server, and a ceramic dripper with optimal flow-rate geometry. The double-walled dripper maintains a stable brew temperature throughout extraction, resulting in more even, flavorful cups. Everything is designed to sit permanently on your countertop as a functional display piece that coffee guests will immediately notice and admire.",
    price: 149.99,
    compareAtPrice: 179.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 211,
    reviews: [
      {
        id: "rev-013-1",
        author: "Lily T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lily",
        rating: 5,
        date: "2026-03-17",
        comment: "This is a work of art on my kitchen counter. Makes incredible coffee too.",
        verified: true,
      },
      {
        id: "rev-013-2",
        author: "Dave P.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dave",
        rating: 5,
        date: "2026-02-28",
        comment: "The gooseneck precision is fantastic. My pour-over routine has never been better.",
        verified: true,
      },
      {
        id: "rev-013-3",
        author: "Sandra K.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sandra",
        rating: 5,
        date: "2026-02-10",
        comment: "Got this as a gift and it's now my most-used kitchen item. Cleanup is easy too.",
        verified: false,
      },
      {
        id: "rev-013-4",
        author: "Jeff M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeff",
        rating: 4,
        date: "2026-01-25",
        comment: "Beautiful setup. I wish the dripper came in a larger size for making two cups at once.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Wood Finish", values: ["Natural Walnut", "Dark Walnut", "White Oak"] },
    ],
    stock: 67,
    status: "active",
    tags: ["coffee", "pour-over", "kitchen", "walnut", "barista"],
    createdAt: "2025-09-15T08:00:00Z",
  },
  {
    id: "prod-014",
    name: "Boucle Accent Armchair",
    slug: "boucle-accent-armchair",
    description: "Sculptural boucle upholstered armchair with solid ash wood legs — the statement piece every living room needs.",
    longDescription:
      "The Boucle Accent Chair has become the defining piece of modern interior design, and this version does the trend justice. The seat and back are upholstered in a thick, chunky boucle fabric with a cloud-like texture that invites you to sink in. Solid ash legs with a brushed brass foot cap elevate the chair with a warm, contemporary contrast. The high back provides genuine neck support, and the wide seat accommodates a variety of sitting positions. Available in four on-trend colorways, it works equally well as a reading chair or as a purely decorative statement piece.",
    price: 649.99,
    compareAtPrice: 799.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80",
      "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 63,
    reviews: [
      {
        id: "rev-014-1",
        author: "Vanessa K.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Vanessa",
        rating: 5,
        date: "2026-03-26",
        comment: "Every single person who visits comments on this chair. It's exactly as beautiful as the photos.",
        verified: true,
      },
      {
        id: "rev-014-2",
        author: "Chris J.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
        rating: 4,
        date: "2026-03-09",
        comment: "Very comfortable and the fabric quality is excellent. Assembly took about 20 minutes.",
        verified: true,
      },
      {
        id: "rev-014-3",
        author: "Hannah W.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hannah",
        rating: 5,
        date: "2026-02-14",
        comment: "The cream boucle looks incredible in my Scandinavian-style living room.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Fabric Color", values: ["Cream", "Warm Gray", "Terracotta", "Sage Green"] },
    ],
    stock: 28,
    status: "active",
    tags: ["chair", "armchair", "boucle", "furniture", "living-room"],
    createdAt: "2025-11-10T08:00:00Z",
  },
  {
    id: "prod-015",
    name: "Ceramic Diffuser & Oil Set",
    slug: "ceramic-diffuser-oil-set",
    description: "Handthrown ceramic ultrasonic diffuser with 6 essential oils — creates a personalized aromatherapy experience.",
    longDescription:
      "Each Ceramic Diffuser is individually handthrown by artisan potters, meaning no two are exactly alike. The ultrasonic diffusion mechanism uses vibration to create a cool mist that disperses essential oils into the air without heat, preserving their therapeutic compounds. With a 400 ml reservoir and three timer settings (1, 3, and 6 hours), it adapts to any space from a small bedroom to an open living area. The set includes six 10 ml oils: lavender, eucalyptus, bergamot, cedarwood, sweet orange, and a proprietary Sleep Blend formulated by certified aromatherapists.",
    price: 79.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 297,
    reviews: [
      {
        id: "rev-015-1",
        author: "Aria B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aria",
        rating: 5,
        date: "2026-03-23",
        comment: "The ceramic is gorgeous — mine has a lovely speckled glaze. The Sleep Blend oil is incredible.",
        verified: true,
      },
      {
        id: "rev-015-2",
        author: "Owen H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Owen",
        rating: 5,
        date: "2026-03-04",
        comment: "Perfect gift for anyone who loves home fragrance. My whole apartment smells amazing.",
        verified: true,
      },
      {
        id: "rev-015-3",
        author: "Zoe C.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe",
        rating: 4,
        date: "2026-02-17",
        comment: "Beautiful quality. Only wish the mist was slightly more powerful for larger rooms.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Ceramic Glaze", values: ["Speckled Cream", "Sage Matte", "Terracotta", "Midnight Blue"] },
    ],
    stock: 143,
    status: "active",
    tags: ["diffuser", "aromatherapy", "essential-oils", "wellness", "ceramic"],
    createdAt: "2025-07-15T08:00:00Z",
  },
  {
    id: "prod-016",
    name: "Modular Bamboo Shelving System",
    slug: "modular-bamboo-shelving-system",
    description: "Sustainable bamboo freestanding shelving system with adjustable shelf heights — organizes any room beautifully.",
    longDescription:
      "The Bamboo Shelving System proves sustainable materials don't require compromise on style or function. Crafted from fast-growing Moso bamboo, each unit is stronger than most hardwoods while being completely renewable. The modular design allows you to adjust shelf heights in 2-inch increments and expand with additional units that lock together seamlessly. A discrete cable management channel runs through the rear uprights, making it ideal for home offices and entertainment setups. Available as a single unit or in linked 2- and 3-bay configurations.",
    price: 229.99,
    compareAtPrice: 279.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80",
    ],
    rating: 4.4,
    reviewCount: 118,
    reviews: [
      {
        id: "rev-016-1",
        author: "Patrick G.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Patrick",
        rating: 5,
        date: "2026-03-19",
        comment: "Sturdy, beautiful, and easy to assemble. The cable management feature saved my home office setup.",
        verified: true,
      },
      {
        id: "rev-016-2",
        author: "Naomi Y.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Naomi",
        rating: 4,
        date: "2026-02-26",
        comment: "Great quality bamboo. The adjustable shelves make it incredibly versatile.",
        verified: true,
      },
      {
        id: "rev-016-3",
        author: "Jake R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jake",
        rating: 4,
        date: "2026-02-06",
        comment: "Bought the 3-bay version for my living room. Instructions were clear and it looks great.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Configuration", values: ["Single Bay", "2-Bay Linked", "3-Bay Linked"] },
    ],
    stock: 54,
    status: "active",
    tags: ["shelving", "bamboo", "sustainable", "storage", "home-office"],
    createdAt: "2025-10-20T08:00:00Z",
  },

  // ── Sports ─────────────────────────────────────────────────────────────────
  {
    id: "prod-017",
    name: "TrailBlazer Carbon Trekking Poles",
    slug: "trailblazer-carbon-trekking-poles",
    description: "100% carbon fibre telescoping trekking poles with anti-shock system and ergonomic cork grips — sold as a pair.",
    longDescription:
      "The TrailBlazer Carbon poles weigh just 230 g each — light enough that you'll forget you're using them until you really need them. The 100% carbon fibre shaft absorbs trail vibration, protecting joints on long descents. The anti-shock mechanism provides an additional 20 mm of cushioning on hard surfaces and disengages via a twist for firm, confident planted poles on ascents. EVA cork grips wick moisture and mold to the shape of your hand over time for a custom feel. The quick-lock three-section design adjusts from 60–135 cm in seconds, and foam-padded wrist straps prevent dropping on scrambles.",
    price: 119.99,
    compareAtPrice: 149.99,
    category: "Sports",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 164,
    reviews: [
      {
        id: "rev-017-1",
        author: "Marcus H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MarcusH",
        rating: 5,
        date: "2026-03-21",
        comment: "Used these on a week-long Appalachian Trail section. My knees have never felt better after that many miles.",
        verified: true,
      },
      {
        id: "rev-017-2",
        author: "Petra V.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Petra",
        rating: 5,
        date: "2026-03-06",
        comment: "Incredibly light. The quick-lock system is solid and never slips even with full body weight.",
        verified: true,
      },
      {
        id: "rev-017-3",
        author: "Lucas B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
        rating: 4,
        date: "2026-02-22",
        comment: "Great poles at a fair price. The cork grips are comfortable but take a few hikes to break in.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Carbon Black", "Forest Green", "Midnight Blue"] },
    ],
    stock: 79,
    status: "active",
    tags: ["hiking", "trekking-poles", "carbon", "outdoor", "backpacking"],
    createdAt: "2025-08-01T08:00:00Z",
  },
  {
    id: "prod-018",
    name: "FlexCore Yoga Mat Pro",
    slug: "flexcore-yoga-mat-pro",
    description: "6 mm thick natural rubber yoga mat with alignment lines, carrying strap, and non-slip texture on both sides.",
    longDescription:
      "The FlexCore Pro is engineered for serious practitioners who demand both performance and sustainability. The 6 mm natural rubber core provides excellent joint cushioning on hard floors while maintaining the firm, responsive feel needed for balance poses. The open-cell top surface creates genuine grip that improves when slightly wet — perfect for hot yoga. Precision alignment lines are laser-printed directly into the mat surface, never on top, so they'll never peel or fade. The mat rolls tight enough to be secured with the included cotton canvas strap and toted to class without a bag.",
    price: 79.99,
    compareAtPrice: 99.99,
    category: "Sports",
    images: [
      "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 437,
    reviews: [
      {
        id: "rev-018-1",
        author: "Yuki S.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki",
        rating: 5,
        date: "2026-03-27",
        comment: "Finally a mat that doesn't slide in hot yoga. The natural rubber grip is everything.",
        verified: true,
      },
      {
        id: "rev-018-2",
        author: "Brian T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brian",
        rating: 5,
        date: "2026-03-13",
        comment: "The alignment lines genuinely improved my practice. My warrior poses are much more symmetrical.",
        verified: true,
      },
      {
        id: "rev-018-3",
        author: "Layla A.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Layla",
        rating: 5,
        date: "2026-02-29",
        comment: "Best yoga mat I've owned and I've tried at least 8. It wipes clean easily and smells fine.",
        verified: true,
      },
      {
        id: "rev-018-4",
        author: "Greg N.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Greg",
        rating: 4,
        date: "2026-01-20",
        comment: "Great mat. Slightly heavier than my previous one due to the rubber but the performance is worth it.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Deep Plum", "Slate Teal", "Terra Rust", "Obsidian Black", "Sand Dune"] },
    ],
    stock: 201,
    status: "active",
    tags: ["yoga", "fitness", "mat", "natural-rubber", "hot-yoga"],
    createdAt: "2025-05-20T08:00:00Z",
  },
  {
    id: "prod-019",
    name: "PowerLift Adjustable Dumbbells",
    slug: "powerlift-adjustable-dumbbells",
    description: "5–52.5 lb selectorized adjustable dumbbell pair — replaces 15 dumbbells in the space of one set.",
    longDescription:
      "The PowerLift Adjustable Dumbbells replace an entire rack of free weights with a single pair. A turn of the selector dial adjusts the weight in 2.5 lb increments from 5 to 52.5 lbs per dumbbell, letting you move between exercises in seconds. The ergonomic contoured handle maintains a consistent diameter across all weight settings for a comfortable grip, and the locking tray mechanism prevents weight plates from rattling or dislodging during exercise. Included base trays protect your floor and keep the unused plates organized. Ideal for home gyms where space is at a premium.",
    price: 349.99,
    compareAtPrice: 429.99,
    category: "Sports",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 283,
    reviews: [
      {
        id: "rev-019-1",
        author: "Steve R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Steve",
        rating: 5,
        date: "2026-03-24",
        comment: "Cleared out an entire rack of dumbbells and replaced them with this pair. Best home gym investment.",
        verified: true,
      },
      {
        id: "rev-019-2",
        author: "Monica J.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Monica",
        rating: 4,
        date: "2026-03-07",
        comment: "Mechanism works smoothly and the dial clicks satisfyingly. Plates feel secure during use.",
        verified: true,
      },
      {
        id: "rev-019-3",
        author: "Henry B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Henry",
        rating: 5,
        date: "2026-02-21",
        comment: "Had these for 6 months and the mechanism still works perfectly. Great build quality.",
        verified: true,
      },
    ],
    variants: [],
    stock: 37,
    status: "active",
    tags: ["dumbbells", "weights", "home-gym", "strength", "adjustable"],
    createdAt: "2025-06-10T08:00:00Z",
  },
  {
    id: "prod-020",
    name: "Aero Road Cycling Helmet",
    slug: "aero-road-cycling-helmet",
    description: "MIPS-equipped aero road helmet with 18 aerodynamically shaped vents and integrated rear light mount.",
    longDescription:
      "Designed in partnership with professional cyclists, the Aero Road Helmet balances protection, aerodynamics, and ventilation in one polished package. The MIPS liner adds rotational impact protection without measurable weight penalty. Eighteen aerodynamically shaped vents are positioned using computational fluid dynamics to maximize airflow to the top of your head while minimizing drag — validated to save 12 seconds over a 40 km time trial compared to conventional round vents. A magnetic buckle makes one-handed closure easy at the start of rides, and the integrated rear light mount accepts any standard cycling light.",
    price: 189.99,
    compareAtPrice: 229.99,
    category: "Sports",
    images: [
      "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80",
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 102,
    reviews: [
      {
        id: "rev-020-1",
        author: "Claire O.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Claire",
        rating: 5,
        date: "2026-03-16",
        comment: "Best fitting helmet I've ever worn. The retention system is incredibly precise.",
        verified: true,
      },
      {
        id: "rev-020-2",
        author: "Miles D.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Miles",
        rating: 4,
        date: "2026-02-23",
        comment: "Great ventilation for summer rides. The magnetic buckle is a game changer.",
        verified: true,
      },
      {
        id: "rev-020-3",
        author: "Tina P.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tina",
        rating: 5,
        date: "2026-02-04",
        comment: "Looks fast standing still. Comfortable enough for 5-hour rides.",
        verified: false,
      },
    ],
    variants: [
      { type: "size", label: "Size", values: ["S (52-56 cm)", "M (55-59 cm)", "L (58-62 cm)"] },
      { type: "color", label: "Color", values: ["Matte Black", "Gloss White", "Team Red"] },
    ],
    stock: 64,
    status: "active",
    tags: ["cycling", "helmet", "MIPS", "road-bike", "aero"],
    createdAt: "2025-09-05T08:00:00Z",
  },

  // ── Accessories ────────────────────────────────────────────────────────────
  {
    id: "prod-021",
    name: "Heritage Leather Bifold Wallet",
    slug: "heritage-leather-bifold-wallet",
    description: "Full-grain vegetable-tanned leather bifold wallet with RFID blocking lining — gets better with age.",
    longDescription:
      "The Heritage Bifold is made from full-grain vegetable-tanned leather sourced from a family-run tannery in Tuscany, Italy. Vegetable tanning is a slow, natural process that uses tree bark extracts rather than chemicals, producing leather that develops a rich patina unique to each owner over years of use. The RFID-blocking carbon fiber lining protects your contactless cards without adding bulk. Six card slots, two bill compartments, and a transparent ID window provide ample organization in a profile slim enough to sit comfortably in a front pocket.",
    price: 89.99,
    category: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 342,
    reviews: [
      {
        id: "rev-021-1",
        author: "Oliver M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver",
        rating: 5,
        date: "2026-03-29",
        comment: "Had mine for 2 years and the patina is stunning. Genuinely improves with age.",
        verified: true,
      },
      {
        id: "rev-021-2",
        author: "Nadia F.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nadia",
        rating: 5,
        date: "2026-03-11",
        comment: "Bought this for my husband and he loves it. Slim profile sits perfectly in his front pocket.",
        verified: true,
      },
      {
        id: "rev-021-3",
        author: "Simon R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Simon",
        rating: 5,
        date: "2026-02-25",
        comment: "The leather quality is exceptional. Smells amazing and already starting to patina nicely.",
        verified: true,
      },
      {
        id: "rev-021-4",
        author: "Kate H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kate",
        rating: 4,
        date: "2026-02-08",
        comment: "Beautiful wallet. Slightly stiff at first but loosens up nicely after a few weeks of use.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Leather Color", values: ["Tan", "Chestnut", "Dark Brown", "Black"] },
    ],
    stock: 167,
    status: "active",
    tags: ["wallet", "leather", "RFID", "bifold", "accessories"],
    createdAt: "2025-07-01T08:00:00Z",
  },
  {
    id: "prod-022",
    name: "Navigator Canvas Backpack",
    slug: "navigator-canvas-backpack",
    description: "26 L waxed canvas backpack with leather accents, laptop sleeve, and organizer panel — built for daily carry.",
    longDescription:
      "The Navigator is the bag you reach for every day. The 16 oz waxed canvas shell is naturally water-resistant and develops a lived-in character with use — wax more scuffs and scratches fade into texture over time. A dedicated padded laptop sleeve fits up to 16-inch machines, while the front organizer panel holds pens, keys, a passport, and a power bank with room to spare. The padded, contoured shoulder straps and back panel are breathable for warm-weather commutes. Solid brass hardware and hand-stitched leather pull tabs will outlast the bag itself.",
    price: 179.99,
    compareAtPrice: 219.99,
    category: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 219,
    reviews: [
      {
        id: "rev-022-1",
        author: "Felix A.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
        rating: 5,
        date: "2026-03-24",
        comment: "Used this daily for 18 months. It's more beautiful now than when I bought it.",
        verified: true,
      },
      {
        id: "rev-022-2",
        author: "Isabelle N.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=IsabelleN",
        rating: 5,
        date: "2026-03-09",
        comment: "Fits my 15-inch laptop, gym clothes, and a full day of work essentials with room to spare.",
        verified: true,
      },
      {
        id: "rev-022-3",
        author: "Dylan C.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dylan",
        rating: 4,
        date: "2026-02-20",
        comment: "Beautiful bag. Organization is excellent. Slightly heavy empty due to the canvas but worth it.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Waxed Olive", "Waxed Navy", "Waxed Black", "Waxed Tan"] },
    ],
    stock: 88,
    status: "active",
    tags: ["backpack", "canvas", "laptop-bag", "commuter", "accessories"],
    createdAt: "2025-08-10T08:00:00Z",
  },
  {
    id: "prod-023",
    name: "Luxury Cashmere Scarf",
    slug: "luxury-cashmere-scarf",
    description: "Grade-A Mongolian cashmere scarf, 200 cm long, 30 cm wide — extraordinarily soft and lightweight.",
    longDescription:
      "Woven from Grade-A cashmere sourced directly from herders in Inner Mongolia, this scarf represents the pinnacle of natural fiber softness. The 28-micron cashmere fibers produce a fabric that feels impossibly light — this scarf weighs under 120 g — yet provides remarkable warmth. The generous 200 x 30 cm dimensions allow for multiple draping styles from a simple loop to a full wrap. Hand-finished fringe edges and a hidden care label maintain a clean, elevated look. Each scarf is packaged in a recyclable gift box, making it a perfect present straight from the bag.",
    price: 119.99,
    compareAtPrice: 149.99,
    category: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 156,
    reviews: [
      {
        id: "rev-023-1",
        author: "Isabella T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella",
        rating: 5,
        date: "2026-03-26",
        comment: "This is the softest thing I have ever touched. Full stop.",
        verified: true,
      },
      {
        id: "rev-023-2",
        author: "Michael S.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
        rating: 5,
        date: "2026-03-10",
        comment: "Bought as a gift and the recipient was floored by the quality. The gift box is lovely too.",
        verified: true,
      },
      {
        id: "rev-023-3",
        author: "Claire P.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ClaireP",
        rating: 5,
        date: "2026-02-23",
        comment: "Lightweight enough to wear indoors, warm enough for cold weather. The perfect scarf.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Ivory", "Camel", "Charcoal", "Burgundy", "Cadet Blue"] },
    ],
    stock: 93,
    status: "active",
    tags: ["scarf", "cashmere", "luxury", "winter", "accessories"],
    createdAt: "2025-10-25T08:00:00Z",
  },
  {
    id: "prod-024",
    name: "Minimal Steel Mesh Watch",
    slug: "minimal-steel-mesh-watch",
    description: "Swiss-movement dress watch with sapphire crystal, stainless steel mesh bracelet, and 50m water resistance.",
    longDescription:
      "The Minimal Steel Mesh Watch draws on mid-century Swiss design principles — nothing unnecessary, everything considered. The 38 mm stainless steel case houses a Swiss-made Ronda 715 quartz movement accurate to ±10 seconds per year. A scratch-resistant sapphire crystal protects the clean white dial, which features only hour indices and a date window at 3 o'clock. The integrated mesh bracelet adjusts without tools using a micro-adjustment slider and folds flat against the wrist for a seamless profile. Water-resistant to 50 m, it transitions from boardroom to weekend without pause.",
    price: 179.99,
    compareAtPrice: 219.99,
    category: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 198,
    reviews: [
      {
        id: "rev-024-1",
        author: "Nathan W.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nathan",
        rating: 5,
        date: "2026-03-28",
        comment: "Beautifully minimal. Gets more compliments than watches costing three times as much.",
        verified: true,
      },
      {
        id: "rev-024-2",
        author: "Sophia D.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia",
        rating: 5,
        date: "2026-03-15",
        comment: "The mesh bracelet is so comfortable I forget I'm wearing it. Exactly what I wanted.",
        verified: true,
      },
      {
        id: "rev-024-3",
        author: "Charlie B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie",
        rating: 4,
        date: "2026-02-27",
        comment: "Great watch for the price. The sapphire crystal makes a real difference in scratch resistance.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Dial Color", values: ["White", "Black", "Champagne"] },
    ],
    stock: 74,
    status: "active",
    tags: ["watch", "minimal", "steel", "swiss", "accessories"],
    createdAt: "2025-09-10T08:00:00Z",
  },
  {
    id: "prod-025",
    name: "Polarized Aviator Sunglasses",
    slug: "polarized-aviator-sunglasses",
    description: "Handcrafted titanium aviator frames with polarized CR-39 lenses — TAC coating reduces glare by 99%.",
    longDescription:
      "Aviator frames have been an icon of cool since 1936, and our Titanium Aviators bring the silhouette into the present with materials unavailable to the original designers. The lightweight titanium frame weighs just 18 g — you'll check that they're still on your face. CR-39 polarized lenses with a TAC multi-layer coating eliminate 99% of horizontal glare and provide 100% UVA/UVB protection. Spring-loaded hinges allow the frame to flex beyond 90 degrees for extended wear without deforming. Each pair comes in a hand-stitched leather case with a chamois cleaning cloth.",
    price: 149.99,
    compareAtPrice: 189.99,
    category: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 271,
    reviews: [
      {
        id: "rev-025-1",
        author: "Ethan G.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan",
        rating: 5,
        date: "2026-03-23",
        comment: "The polarization is the best I've tried — no colour distortion, just pure clarity.",
        verified: true,
      },
      {
        id: "rev-025-2",
        author: "Rosa M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rosa",
        rating: 5,
        date: "2026-03-07",
        comment: "So lightweight I wore them for 8 hours hiking without any pressure on my nose.",
        verified: true,
      },
      {
        id: "rev-025-3",
        author: "Alex K.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
        rating: 4,
        date: "2026-02-19",
        comment: "Beautiful glasses. The leather case is a lovely touch that justifies the price.",
        verified: true,
      },
      {
        id: "rev-025-4",
        author: "Megan T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Megan",
        rating: 5,
        date: "2026-01-31",
        comment: "Replaced my previous $200 sunglasses with these. I prefer these in every way.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Frame Color", values: ["Gold/Brown", "Silver/Gray", "Gunmetal/Green"] },
    ],
    stock: 112,
    status: "active",
    tags: ["sunglasses", "aviator", "polarized", "titanium", "accessories"],
    createdAt: "2025-06-25T08:00:00Z",
  },

  // ── Additional Products (mix of categories) ─────────────────────────────────
  {
    id: "prod-026",
    name: "Compact Espresso Machine",
    slug: "compact-espresso-machine",
    description: "15-bar semi-automatic espresso machine with integrated burr grinder and steam wand — café quality at home.",
    longDescription:
      "The Compact Espresso Machine democratizes café-quality coffee without the café footprint. The 15-bar Italian pump delivers the pressure required for genuine espresso extraction, and the built-in conical burr grinder with 5 grind settings ensures you're always working with freshly ground beans. The commercial-style steam wand produces microfoam suitable for latte art with a little practice. A pre-infusion function gently saturates the puck before full extraction, pulling out complex flavors that less sophisticated machines miss entirely. The thermoblock heating system reaches brew temperature in under 30 seconds.",
    price: 399.99,
    compareAtPrice: 499.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 188,
    reviews: [
      {
        id: "rev-026-1",
        author: "Lorenzo G.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lorenzo",
        rating: 5,
        date: "2026-03-18",
        comment: "Cancelled my coffee shop subscription after getting this. It pays for itself in a month.",
        verified: true,
      },
      {
        id: "rev-026-2",
        author: "Diane H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diane",
        rating: 4,
        date: "2026-02-29",
        comment: "Makes excellent espresso. Takes a week to dial in the grind but worth the effort.",
        verified: true,
      },
      {
        id: "rev-026-3",
        author: "Anthony B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anthony",
        rating: 5,
        date: "2026-02-13",
        comment: "The steam wand is impressive for a home machine. My flat whites rival local cafés.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Brushed Stainless", "Matte Black", "Cream White"] },
    ],
    stock: 41,
    status: "active",
    tags: ["espresso", "coffee", "kitchen", "appliance", "barista"],
    createdAt: "2025-11-05T08:00:00Z",
  },
  {
    id: "prod-027",
    name: "Merino Running Socks 3-Pack",
    slug: "merino-running-socks-3-pack",
    description: "Cushioned Merino wool running socks with anatomic left/right construction and blister-resistant flat seams.",
    longDescription:
      "Running socks are the most underappreciated piece of running gear, and the Merino Running Socks exist to correct that. An 85% Merino blend regulates temperature naturally — warm in cold weather, cool in heat — while wicking moisture away from the skin more effectively than synthetic fabrics. The anatomically shaped left and right construction eliminates bunching, and the flat-knit seams across the toe box remove the number-one cause of runner's blisters. A graduated compression ankle band supports the Achilles without constricting. These socks hold up to machine washing without wool's typical felting issues thanks to a superwash process.",
    price: 34.99,
    category: "Sports",
    images: [
      "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 512,
    reviews: [
      {
        id: "rev-027-1",
        author: "Jenna L.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jenna",
        rating: 5,
        date: "2026-03-31",
        comment: "No blisters in 6 months of marathon training. These are the only running socks I'll buy.",
        verified: true,
      },
      {
        id: "rev-027-2",
        author: "Kevin M.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin",
        rating: 5,
        date: "2026-03-16",
        comment: "Comfortable for summer and winter runs alike. The Merino really does regulate temperature.",
        verified: true,
      },
      {
        id: "rev-027-3",
        author: "Amy T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amy",
        rating: 5,
        date: "2026-02-28",
        comment: "Bought 4 packs after trying the first one. Never going back to synthetic running socks.",
        verified: true,
      },
    ],
    variants: [
      { type: "size", label: "Shoe Size", values: ["US 4-6", "US 6.5-9", "US 9.5-12", "US 12+"] },
      { type: "color", label: "Color", values: ["Black/Gray", "White/Blue", "Charcoal/Orange"] },
    ],
    stock: 318,
    status: "active",
    tags: ["socks", "merino", "running", "athletic", "3-pack"],
    createdAt: "2025-05-15T08:00:00Z",
  },
  {
    id: "prod-028",
    name: "Titanium Carabiner Keychain",
    slug: "titanium-carabiner-keychain",
    description: "Aerospace-grade titanium D-ring carabiner with a locking gate — organizes up to 12 keys silently.",
    longDescription:
      "End the jangle. The Titanium Carabiner Keychain is machined from 6AL-4V aerospace-grade titanium — the same alloy used in aircraft fasteners — making it genuinely lighter than most steel key rings while being stronger. The locking screw gate holds your keys captive until you deliberately choose to release them, eliminating the keys-falling-off-the-ring problem entirely. Rubber-lined key loops prevent metal-on-metal contact, keeping your keys silent in your pocket. Designed to clip directly to a belt loop or bag strap with the large D-ring, it's for people who treat their keys as an EDC essential.",
    price: 39.99,
    category: "Accessories",
    images: [
      "https://images.unsplash.com/photo-1548036161-a3e4e2c6ebfe?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 389,
    reviews: [
      {
        id: "rev-028-1",
        author: "Kyle A.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kyle",
        rating: 5,
        date: "2026-03-30",
        comment: "Incredibly light and the locking gate is perfectly engineered. My keys are finally silent.",
        verified: true,
      },
      {
        id: "rev-028-2",
        author: "Sara B.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sara",
        rating: 5,
        date: "2026-03-14",
        comment: "Had this for a year with daily use. Zero scratches, zero wear. Titanium is worth it.",
        verified: true,
      },
      {
        id: "rev-028-3",
        author: "Ryan H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RyanH",
        rating: 4,
        date: "2026-02-26",
        comment: "Solid product. The locking mechanism does take getting used to but you'll appreciate it.",
        verified: true,
      },
    ],
    variants: [
      { type: "color", label: "Finish", values: ["Natural Titanium", "Black PVD", "Blue Anodized"] },
    ],
    stock: 245,
    status: "active",
    tags: ["keychain", "titanium", "carabiner", "EDC", "accessories"],
    createdAt: "2025-04-20T08:00:00Z",
  },
  {
    id: "prod-029",
    name: "Studio Monitor Bookshelf Speakers",
    slug: "studio-monitor-bookshelf-speakers",
    description: "Active 5-inch studio monitor speakers with Class-D amplifier, balanced XLR inputs, and acoustic room correction.",
    longDescription:
      "Designed for producers, engineers, and music lovers who demand accuracy, the Studio Monitor Bookshelf Speakers deliver flat frequency response from 45 Hz to 25 kHz. The 5-inch woven-composite woofer and 1-inch silk dome tweeter are each driven by their own Class-D amplifier for a combined 100 W of clean power. A built-in acoustic correction DSP lets you dial in custom EQ curves to compensate for room acoustics — particularly useful near walls or corners. Balanced XLR and unbalanced RCA inputs accommodate professional and consumer equipment alike, and a USB-C audio input allows direct computer connection.",
    price: 449.99,
    compareAtPrice: 549.99,
    category: "Electronics",
    images: [
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
      "https://images.unsplash.com/photo-1498049794991-d7b9ac80a08f?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 127,
    reviews: [
      {
        id: "rev-029-1",
        author: "DJ K.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DJK",
        rating: 5,
        date: "2026-03-22",
        comment: "These replaced monitors twice the price in my home studio. The imaging is exceptional.",
        verified: true,
      },
      {
        id: "rev-029-2",
        author: "Penny R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Penny",
        rating: 5,
        date: "2026-03-05",
        comment: "Using as desktop speakers for music listening. The detail retrieval is stunning.",
        verified: true,
      },
      {
        id: "rev-029-3",
        author: "George F.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=George",
        rating: 4,
        date: "2026-02-17",
        comment: "Room correction works well. Setup was straightforward and the sound is natural and balanced.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Black", "White"] },
    ],
    stock: 29,
    status: "active",
    tags: ["speakers", "studio-monitors", "audio", "hi-fi", "electronics"],
    createdAt: "2025-12-10T08:00:00Z",
  },
  {
    id: "prod-030",
    name: "Performance Running Jacket",
    slug: "performance-running-jacket",
    description: "Ultralight wind-resistant running jacket with reflective details, thumb loops, and a rear zip pocket.",
    longDescription:
      "When the weather is iffy but you still need to get your miles in, the Performance Running Jacket is the answer. Weighing just 125 g, it packs into its own chest pocket for easy stashing pre or post-run. The 20-denier ripstop fabric is wind-resistant and shower-proof with a DWR finish, and the laser-perforated underarms provide ventilation without sacrificing coverage. Full-length 360-degree reflective detailing makes you visible from any angle in low-light conditions — a safety feature that shouldn't be overlooked. Articulated patterning and stretch-woven side panels allow unrestricted arm swing throughout your stride cycle.",
    price: 129.99,
    compareAtPrice: 159.99,
    category: "Clothing",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
      "https://images.unsplash.com/photo-1556821840-3a63f4d732eb?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 173,
    reviews: [
      {
        id: "rev-030-1",
        author: "Dani H.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dani",
        rating: 5,
        date: "2026-03-27",
        comment: "This has become my go-to for morning runs. Light, breathable, and the reflective details are great.",
        verified: true,
      },
      {
        id: "rev-030-2",
        author: "Chris V.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ChrisV",
        rating: 5,
        date: "2026-03-10",
        comment: "Packs so small I keep it in my running belt as a backup. The packable pocket is smart design.",
        verified: true,
      },
      {
        id: "rev-030-3",
        author: "Sam F.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SamF",
        rating: 4,
        date: "2026-02-24",
        comment: "Great jacket. Runs slightly long in the body but that's fine for running coverage.",
        verified: false,
      },
    ],
    variants: [
      { type: "size", label: "Size", values: ["XS", "S", "M", "L", "XL"] },
      { type: "color", label: "Color", values: ["Neon Yellow", "Coral Red", "Electric Blue", "Black"] },
    ],
    stock: 95,
    status: "active",
    tags: ["jacket", "running", "windproof", "reflective", "packable"],
    createdAt: "2025-07-20T08:00:00Z",
  },
  {
    id: "prod-031",
    name: "Bamboo Cutting Board Set",
    slug: "bamboo-cutting-board-set",
    description: "Set of 3 end-grain bamboo cutting boards with juice grooves, rubber feet, and natural antimicrobial properties.",
    longDescription:
      "End-grain bamboo is kinder to knife edges than most hardwoods, self-healing minor cuts for a board that stays smooth longer. This set of three graduated boards (small, medium, large) covers every food prep task from snacking to full meal prep. Deep juice grooves on the large and medium boards channel runoff away from the work surface and prevent countertop mess when carving meat or slicing ripe tomatoes. All three boards feature rubberized non-slip feet and hang holes for storage. Bamboo's natural density makes it naturally antimicrobial, but the boards are also finished with food-safe mineral oil for added protection.",
    price: 69.99,
    compareAtPrice: 89.99,
    category: "Home & Living",
    images: [
      "https://images.unsplash.com/photo-1510127034890-ba27f445630e?w=800&q=80",
      "https://images.unsplash.com/photo-1493663284031-b7e3191512a7?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 443,
    reviews: [
      {
        id: "rev-031-1",
        author: "Patricia A.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia",
        rating: 5,
        date: "2026-03-31",
        comment: "Best cutting boards I've used. The end-grain construction is noticeably gentler on my knives.",
        verified: true,
      },
      {
        id: "rev-031-2",
        author: "Tom W.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=TomW",
        rating: 5,
        date: "2026-03-14",
        comment: "Beautiful set. The juice grooves work great and the rubber feet keep them firmly in place.",
        verified: true,
      },
      {
        id: "rev-031-3",
        author: "Maria C.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
        rating: 4,
        date: "2026-02-28",
        comment: "Very happy with these. They arrived well-oiled and ready to use immediately.",
        verified: true,
      },
    ],
    variants: [],
    stock: 127,
    status: "active",
    tags: ["cutting-board", "bamboo", "kitchen", "cooking", "sustainable"],
    createdAt: "2025-04-10T08:00:00Z",
  },
  {
    id: "prod-032",
    name: "Resistance Band Training Set",
    slug: "resistance-band-training-set",
    description: "Set of 5 latex-free resistance bands (10–50 lb) with handles, ankle straps, door anchor, and carry bag.",
    longDescription:
      "The Resistance Band Training Set delivers a full-gym experience in a bag that weighs under 1 kg. Five bands ranging from 10 to 50 lb resistance can be stacked on the included comfort-grip handles for up to 150 lb of combined resistance — enough to challenge even advanced lifters. Flat woven fabric construction (not round tubing) distributes load more evenly and resists rolling or snapping. Ankle straps allow lower-body exercises, the door anchor sets up in seconds, and a laminated exercise chart with 30 moves gets beginners started immediately. Everything packs into the included mesh carry bag for home, hotel, or outdoor training.",
    price: 49.99,
    compareAtPrice: 64.99,
    category: "Sports",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
      "https://images.unsplash.com/photo-1535131749619-0be7aec49f5d?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 628,
    reviews: [
      {
        id: "rev-032-1",
        author: "Tiffany R.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tiffany",
        rating: 5,
        date: "2026-03-29",
        comment: "Travel with these everywhere. Can replicate almost every gym exercise with just these bands.",
        verified: true,
      },
      {
        id: "rev-032-2",
        author: "Derek P.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DerekP",
        rating: 5,
        date: "2026-03-13",
        comment: "The flat band design is much more comfortable than tube bands. No skin pinching.",
        verified: true,
      },
      {
        id: "rev-032-3",
        author: "Olivia T.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=OliviaT",
        rating: 4,
        date: "2026-02-26",
        comment: "Great value. The exercise chart is beginner-friendly and the handles are very comfortable.",
        verified: true,
      },
      {
        id: "rev-032-4",
        author: "Justin W.",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Justin",
        rating: 4,
        date: "2026-02-09",
        comment: "Had these for 4 months now. No snapping, no fraying. Very impressed with the durability.",
        verified: false,
      },
    ],
    variants: [
      { type: "color", label: "Color", values: ["Black", "Gray/Blue"] },
    ],
    stock: 214,
    status: "active",
    tags: ["resistance-bands", "fitness", "home-gym", "portable", "strength"],
    createdAt: "2025-03-01T08:00:00Z",
  },
]
